### ISSUE TITLE
Need to be able to limit the number of commands placed in a function

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#10]
Under basic programming we have levels where we assume students will create a left turn function because they can only use two commands and one is the "rocket." But in testing some kids immediately realize they can meet any limitation requirements by rewriting rocket to do everything.

So we should also limit the number of commands that can be placed inside rocket so that they will be forced to create a second function to turn left. 

In future levels we will probably also need this capability.

**Comment by giftedprimate** [comment]
This shouldn't be to difficult to implement. I can include this with the next release.
