### ISSUE TITLE
Possible bug on 'Clean Up More' level

### ISSUE THREAD

**Issue by chewmagroo** [JWWeatherman/math_bot#102]
Had this issue (see video zip file). Refreshing the page fixed it.
[Bug_01.zip](https://github.com/JWWeatherman/math_bot/files/2108937/Bug_01.zip)

**Comment by giftedprimate** [comment]
Can you create this video in google drive please?

**Comment by chewmagroo** [comment]
https://drive.google.com/file/d/1GKCeHYzsPTMdbMNKIGET6LViRsFeHmTy/view?usp=sharing

**Comment by giftedprimate** [comment]
Closing for now.
