### ISSUE TITLE
Ability to Empty Out a Function with a Single Click

### ISSUE THREAD

**Issue by dy24703** [JWWeatherman/math_bot#103]
I was thinking that a useful enhancement for the game would be to add a "clear" button to the functions. I have found the lack of this to be kind of annoying when I need to empty a function of commands by dragging them out. 

![image](https://user-images.githubusercontent.com/40341596/41512435-2bb6d3ce-7256-11e8-8065-51ce207621c7.png)

**Comment by dy24703** [comment]
Obviously I am not implying that removing two commands as pictured is very difficult, but sometimes you end up with quite a few commands inside of a function and need to clear it out. This would be helpful if a kid makes a mistake somewhere in assembling a function and just wants to start over.

**Comment by chewmagroo** [comment]
I was going to suggest the exact same thing. Another imrpovement in this situation would be instead of having to drag commands out of the function window you could simply click on them.

**Comment by smh69** [comment]
as of at least 20180704, can confirm this works in production.

**Comment by giftedprimate** [comment]
This feature is complete.
