### ISSUE TITLE
Ability to re-arrange and remove functions

### ISSUE THREAD

**Issue by chewmagroo** [JWWeatherman/math_bot#104]
I think the ability to re-arrange functions (possibly commands too) and remove/delete them would improve gameplay. It can become a bit confusing when there are a build up of unwanted functions.
<img width="1268" alt="math_bot_06" src="https://user-images.githubusercontent.com/28259233/41548031-b08f9cac-7319-11e8-8e13-90f5887f755a.png">

**Comment by dy24703** [comment]
I agree with this. There were many times I wanted to re-arrange or remove functions. It doesn't necessarily interfere with the games functionality but maybe something to think about when you start to fine tune everything.

**Comment by giftedprimate** [comment]
I have implemented the ability to sort the functions. 

As for the remove feature I'll try to get to it before the next release and I do agree that this should be done.

**Comment by giftedprimate** [comment]
Sort feature is released, I will create a new issue for delete function function.
