### ISSUE TITLE
Planet 2 "Pickup 2" should be deleted.

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#105]
It is redundant and slightly out of place since it seems to be a level where you would not use the navigate function (otherwise it is the same as "pickup 2 with function"), but the gamer has just created the navigate function so it is weird they wouldn't use it.

![cursor_and_math_bot_and_slack_-_mathbot](https://user-images.githubusercontent.com/32912678/41548450-10dd4998-72f1-11e8-8263-338b76446151.jpg)

**Comment by giftedprimate** [comment]
I'll remove it as part of the video release.
