### ISSUE TITLE
'Create a turn left function' bug.

### ISSUE THREAD

**Issue by chewmagroo** [JWWeatherman/math_bot#106]
See attached screen recording.

[Bug_02.zip](https://github.com/JWWeatherman/math_bot/files/2112127/Bug_02.zip)

**Comment by giftedprimate** [comment]
Can you create this video in google drive please?

**Comment by giftedprimate** [comment]
Sure, when you click the share button there will be an option 'share with anyone who has the link', just select that option then send the link.

Thanks!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by chewmagroo** [comment]
Here's the link to this file plus the other one you requested.
https://drive.google.com/file/d/1u9-J3zgiUsEyShTrUMjR9NuE5wwrd2SR/view?usp=sharing
https://drive.google.com/file/d/1GKCeHYzsPTMdbMNKIGET6LViRsFeHmTy/view?usp=sharing

**Comment by JWWeatherman** [comment]
I just verified this bug has been fixed. @chewmagroo please let me know if you can still reproduce it or if it's fixed for you too.
