### ISSUE TITLE
Ad blocker hiding all images

### ISSUE THREAD

**Issue by clarkmoody** [JWWeatherman/math_bot#109]
Maybe my ad blocker is too strict, but all image assets coming from `res.cloudinary.com` are blocked.

![screen shot 2018-06-19 at 4 40 07 pm](https://user-images.githubusercontent.com/1562417/41725584-c725761c-7535-11e8-8089-3b2d62bc5596.png)

**Comment by clarkmoody** [comment]
@giftedprimate Thanks for following through. I'm using Pi-Hole, which blocks at the DNS lookup level, so the filenames are not the problem.

The site is working properly now, so maybe the CDN changed. Whatever the case, I can close this ticket.

**Comment by giftedprimate** [comment]
@clarkmoody thanks!
