### ISSUE TITLE
Bug on level "Pick up 3"

### ISSUE THREAD

**Issue by jordanBTCplz** [JWWeatherman/math_bot#111]
I am running into this issue where the robot can not put down the kitties after picking them up. I went through this level and experienced this issue roughly five times. After capturing the video that is attached and trying this level again, but using a function in a different way, it worked. After that I attempted to complete the level exactly the way I did in the video. I am now able to complete the level without issues. Issue was noticed on firefox web browser.

[mathbot bug on level pick up 3.zip](https://github.com/JWWeatherman/math_bot/files/2130375/mathbot.bug.on.level.pick.up.3.zip)

**Comment by giftedprimate** [comment]
I believe this is do to a bug that I fixed today. The issue is that occasionally when editing a function the db was not getting updated with the change. Please look forward to a fix on the next release.

**Comment by giftedprimate** [comment]
Also can you create this video in google drive by chance?

**Comment by dy24703** [comment]
Ya I will work on that. Is that how you guys would prefer all videos be done on here?

**Comment by giftedprimate** [comment]
Yes either drive or YouTube would be great. Thanks for the feed back, it is very helpful.

**Comment by dy24703** [comment]
Hey what's the name or email you want me to share these videos to when I put them into google drive? Sorry it took me a little while to get back.

**Comment by giftedprimate** [comment]
Just click the `share with anyone who has the link` radio button then past the link here.

Thanks!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by dy24703** [comment]
https://drive.google.com/open?id=14niu5pWWF0xdGQu0VvTJIAZF-NzWuMPI

That's a cool feature. Thanks for your patience.

**Comment by JWWeatherman** [comment]
Verified fixed on chrome on mac. @jordanBTCplz Can you verify on your windows box?

**Comment by giftedprimate** [comment]
Closing as this issue should be remedied already.
