### ISSUE TITLE
Where are the Kitties?

### ISSUE THREAD

**Issue by dy24703** [JWWeatherman/math_bot#112]
On the level "Navigate," the instructions say to "get to the kitties" and there are no kitties to navigate to.

![where are the kitties](https://user-images.githubusercontent.com/40341596/41815152-ea101a3c-772f-11e8-9241-0b7b30993ba7.png)

**Comment by chewmagroo** [comment]
I think I already posted this issue - #101 
I'm pretty sure it should say 'Create a function to get to the portal'

**Comment by dy24703** [comment]
You are correct. Thanks for pointing that out.
