### ISSUE TITLE
Differentiate commands and functions with colour.

### ISSUE THREAD

**Issue by chewmagroo** [JWWeatherman/math_bot#113]
Something like this might help avoid confusion by visually differentiating between commands and functions.
![math_bot_04](https://user-images.githubusercontent.com/28259233/41871998-84392b56-78b8-11e8-8335-ddf12df360c7.jpg)

**Comment by chewmagroo** [comment]
Sounds like I'll need to see those next levels to get an idea of what you mean. If this is the way you will colour conditionals would it not make sense to colour commands and functions the same way? Just use different colours.

**Comment by giftedprimate** [comment]
@chewmagroo Just an FYI that we have differentiated the primitive functions and user built functions. You can expect to see this change in the next release.
