### ISSUE TITLE
Scroll up button not working inside custom function

### ISSUE THREAD

**Issue by babakar7** [JWWeatherman/math_bot#118]
When creating a new function and trying to reference simpler actions that require scrolling up to access them, it doesn't work. 
<img width="1273" alt="capture d ecran 2018-06-30 a 17 14 58" src="https://user-images.githubusercontent.com/40721549/42127488-2c5f6de4-7c89-11e8-8dda-1a294aa03da2.png">

**Comment by giftedprimate** [comment]
This should work fine. Can you tell me what device you are using?

**Comment by babakar7** [comment]
I'm using chrome on a macbook pro. I tested this with Safari and it works fine though

**Comment by giftedprimate** [comment]
It should work fine on chrome also (that is what I am using). Are you using a 13inch macbook?

**Comment by babakar7** [comment]
Yes I am

**Comment by giftedprimate** [comment]
Ok, cool. 

I'll pull it up on my MacBook to make the appropriate adjustments for the next release. I'm pretty sure this is related to styling. 

Thanks!

**Comment by babakar7** [comment]
Great
