### ISSUE TITLE
Stuck in middle of function

### ISSUE THREAD

**Issue by babakar7** [JWWeatherman/math_bot#120]
My bot is stuck in the middle of a function. It still has many instructions to follow, but just freezes here. 
<img width="1275" alt="capture d ecran 2018-06-30 a 19 22 23" src="https://user-images.githubusercontent.com/40721549/42128433-1ee0ddee-7c9b-11e8-8bf6-252019b6efcd.png">

2nd image is the function in question. It is stuck at the sun icon. (which is just 6 steps forward that it hasn't completed) 
<img width="1265" alt="capture d ecran 2018-06-30 a 19 24 24" src="https://user-images.githubusercontent.com/40721549/42128448-640b2226-7c9b-11e8-88d8-35b096b07164.png">

**Comment by console-rastling** [comment]
Is it possible one of the function in the middle of all kitties is recursively calling itself?  That would cause the function to only run up to that function, then it would loop until we ran 10k steps. 

We are still thinking about adding a pre-check for things like this.  Its not incorrect really, its just confusing and so users like you might want a warning.  Let us know.

**Comment by JWWeatherman** [comment]
I'm going to close this for now. We will probably address it best by adding more "debug" features over time. More visibility into what code the robot is executing.
