### ISSUE TITLE
recursive func within a func doesn't halt, even on finalAnswer

### ISSUE THREAD

**Issue by smh69** [JWWeatherman/math_bot#133]
Can reproduce in level=Recursion, steps=[Cleanup, CleanUpMore]

maybe this is an error, or maybe Im just lost;  In my lostness, I believe the following are logically the same.

below assumes that walk(), pickUp(), and putDown() are NOT user-defined

Does not work:
def walkPickUp: walk(); pickUp()
def r_putDown: putDown(); r_putDown()
def myMain: walkPickUp() ... 9 times; r_putDown()
def main: myMain() // lands on final answer, loops forever in r_putDown

Does work:
def walkPickUp: same as above
def r_putDown: same as above
def myMain: walkPickUp() ... 9 times
def main: myMain(); r_putDown() // Nice!

...back in a few, Trying to wrap my head around the code base, will share my thoughts if I can figure out where this might be happening. -spencer

**Comment by smh69** [comment]
update: an admission: Im noob to scala and this codebase, stuck trying to figure out the app/compiler/Compiler.scala sections of processBoard(GridMap) and processBoard(JsArray) where convertedToElements is being set, but quite far from understanding ie: clueless.  Don't hold out, for me, if you know what the issue is, or know that its not an issue at all.  I'll appreciate info shared/learned and your commit message.  -spencer

**Comment by smh69** [comment]
update: now looking into app/processor/Processor.scala in recursive private execute() but I dont see any difference of processing between the main program and a user func (except when the func only has a single function op inside... which is not my case).  Wondering if source code that Im looking at is what is really running in production (in which case Im spinning my wheels), but suspecting I just need to keep reading/understanding code.   ....or perhaps I need to install on my machine and try stepping through locally... but id rather just read for now.

**Comment by giftedprimate** [comment]
Console-rastling is constantly working on the compiler therefore it is probably not a good idea to work on it to much. I pretty much only work on it if I need to inject some logic related to a different actor. When we meet this Tuesday I will show him this issue so that he can respond (for fear that I may put my foot in my mouth ;) ) 

I do know he is using streams for the frames, and streams can become very cryptic to follow. Also (as you may have noticed) the compiler is immutable which is pretty cool and for those of us from the OOP it seams impossible!   

Thanks!

**Comment by giftedprimate** [comment]
Oh and the current master is what is in production currently. Also we are keeping each release in a branch, this release is 0.02-alpha. 

And to answer the question of main running the same as user built functions. This is true, if you look at `app/model/defaultFunctions.scala` you will notice that main is the same data type as the functions and commands. 

When we store functions inside other functions we are removing all but the necessary parts for ui rendering and identification (commandId and created_id) then the compiler references the `func` from the users `active funcs`. 

Thought this may help, I'll be sure to show Console this on Tues. Thanks!

**Comment by console-rastling** [comment]
Thanks smh69.  The code that evaluates the program to see if it the solution featured recursion couldn't detect a recursive function more than one layer deep.  We replaced the detector with a recursive function.  You can see it in the [diff](https://github.com/JWWeatherman/math_bot/commit/beea00e70863c15640eea47e3f2fccd16c97c7e2).

GP will mark this issue closed when the fix gets deployed.  

Feel free to ask any questions or for explanations of code anytime.  We learn from each other that way.

**Comment by giftedprimate** [comment]
Just re deployed with the fix for this level, closing issue.

**Comment by smh69** [comment]
nicely done!
