### ISSUE TITLE
Setup XeroForo

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#145]
Need to get this forum setup and configured for invite only for students of the JW Weatherman course on cryptocurrency trading and investing and also another copy for mathbot.com.

https://xenforo.com/purchase/

**Comment by JWWeatherman** [comment]
JW will reimburse any costs.

**Comment by dy24703** [comment]
Domain is up and running. Nate found a web developer to get the forum set up to Nate's liking.

**Comment by NateAgapi** [comment]
This is done.
