### ISSUE TITLE
after winning level 4 you cannot play level 5

### ISSUE THREAD

**Issue by eth-is-a-security** [JWWeatherman/math_bot#151]
On level 4, after completing the level so that it shows stars on the level select screen for level 4, level 5 is not unlocked. On top of that when I tried to complete level 4 again I received try again despite using the correct code to solve the level.

code: various functions which total to 9 walk blocks, Turn right, function with 4 walk blocks, turn right, various functions which total to 9 walk blocks, Turn right,  function with 2 walk blocks, Turn right, various functions which total to 5 walk blocks. END

**Comment by giftedprimate** [comment]
You must use recursion to pass these levels now. Be sure you are using a function that calls itself.
