### ISSUE TITLE
Need a quick way to add functions instead of dragging them

### ISSUE THREAD

**Issue by virindiparadox** [JWWeatherman/math_bot#166]
It will save time and reduce annoyance/boredom if there was a way to add functions to the main play bar (or to a newly created function) instead of having to manually drag each command. 

Some way of being able to add them faster, such as by "Shift / Control / Alt / Middle or Double Clicking" would be a huge improvement.

**Comment by giftedprimate** [comment]
@virindiparadox  The designers decided to keep the options for adding functions very minimal to avoid confusion for young children (in tests we ran children would accidentally add functions with the double click). In future releases we will be adding a Lisp (like) interface for the more advanced students to be able to use an actual programming language to program the robot. 

That said I will leave this issue open for discussion and in case @JWWeatherman has something to add. 

Thanks!

**Comment by virindiparadox** [comment]
That makes sense. For advanced users it would be nice to have this type of option.

**Comment by s3rvant** [comment]
Perhaps a gear or hamburger icon which reveals menu to allow user to select options such as double-click, hotkey-click and/or lisp interface. Can still default to drag-drop only.

**Comment by JWWeatherman** [comment]
I'm closing this for now I think it's best addressed by the lisp feature. After we have that "expert mode" we can consider adding an "intermediate mode" that adds hot keys or a double click when not on tablets, but my guess is that we won't really want it anymore.
