### ISSUE TITLE
Dragging a function from the 2nd function bar scrolls up the function window to the 1st bar

### ISSUE THREAD

**Issue by virindiparadox** [JWWeatherman/math_bot#167]
Dragging a function to the main play bar from the 2nd function bar makes the function window scroll up depending on how fast you drag it (you have to be really quick to make it not scroll). Usually it will scroll up by half and cut off all of the named text, and then if you drag it again it will start showing the first bar. This means you then have to scroll down in order to drag the next function up to the main play bar.

**Comment by giftedprimate** [comment]
@virindiparadox this is fixed and will be part of the next release. We have made major improvements to the UI overall.

**Comment by virindiparadox** [comment]
Great!
