### ISSUE TITLE
Recursion level 14 needs to allow one more function

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#173]
I can't beat the level as it requires at least 1 more function.

**Comment by JWWeatherman** [comment]
Scratch that. We need to move the portal one square to the left maybe too. Let's wait until we have more time to polish this one. It's not urgent as it works good enough and isnt an obvious fix.

**Comment by giftedprimate** [comment]
Closing because we are dealing with this in issue #204
