### ISSUE TITLE
Clicking on a function inside main should also open the edit box

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#178]
I think there might be a good reason we didn't do this, but it would be less confusing if we could click on a function to edit it, even if it has already been added to main.

This issue is mainly to keep track of why this can't or shouldn't be done.

**Comment by giftedprimate** [comment]
@JWWeatherman I was needing something to do so I want ahead and implemented this feature and deployed it to preprod, let me know what you think.

**Comment by giftedprimate** [comment]
Deployed to prod, leaving open so JW can inspect at a later time.

**Comment by JWWeatherman** [comment]
Such a great UX improvement. Good deal.
