### ISSUE TITLE
If I have an oddly sized window mathbot displays poorly

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#180]
Not sure this is critical, but if we fix this it might help with other screen size bugs.
![math_bot](https://user-images.githubusercontent.com/32912678/44222868-f172f300-a153-11e8-9fc8-1012c3526ef0.gif)

**Comment by giftedprimate** [comment]
This is all part of the mobile optimization issue and is a work in progress.

**Comment by JWWeatherman** [comment]
Closing as duplicate of #5
