### ISSUE TITLE
After clicking stop the robot doesn't return home and the play button is still gone

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#181]
This was on level 9 in Recursion.

![math_bot](https://user-images.githubusercontent.com/32912678/44223175-d359c280-a154-11e8-8e6b-c595d52c4e76.gif)

**Comment by giftedprimate** [comment]
Related to issue #80

**Comment by giftedprimate** [comment]
Console and I will need to look at this together. The compiler is not responding to halt requests with non recursive functions.

**Comment by giftedprimate** [comment]
Deployed,
