### ISSUE TITLE
On some screen-sizes the location of things on the screen change when playing a hint

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#183]
This is a little disorienting and might be a hint for some of the other ui bugs at various screen sizes.

**Comment by giftedprimate** [comment]
This is because we only have media queries set up through iPad pro size. I have not done any querying for random browser window sizes.

**Comment by giftedprimate** [comment]
This is ongoing and is part of #5

**Comment by giftedprimate** [comment]
Closing since this will be resolved by issue #292
