### ISSUE TITLE
Robot doesn't respond on recursion level 12

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#185]
I can't complete the level using "clean comb" function. After populating it and hitting play the robot doesn't respond. If I clear it out and start with just a few commands it works, but after adding most of the commands I need to pass the level the robot returns to freezing when I hit play.

**Comment by giftedprimate** [comment]
I cannot recreate this bug. When I tested this in prod it worked fine.

**Comment by giftedprimate** [comment]
Bug was fixed by rebuilding u turn function, unknown reasons. Will need to keep an eye out for this.

**Comment by JWWeatherman** [comment]
Closing this as I think it has been fixed.
