### ISSUE TITLE
In a 1200 x 900 window the saucer / profile link is not clickable

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#186]
Using Chrome on a mac.

The Saturn is clickable, but it doesn't look like it should be.
![math_bot](https://user-images.githubusercontent.com/32912678/44224939-0ce0fc80-a15a-11e8-83ab-05876b62fe30.gif)

**Comment by giftedprimate** [comment]
That entire image is clickable. I will make a media query for macbooks to solve this problem.

**Comment by giftedprimate** [comment]
@JWWeatherman a fix for this is deployed to pre-prod. Please close this issue after you approve.

**Comment by JWWeatherman** [comment]
Verified fixed.
