### ISSUE TITLE
No hints available error shown no conditionals level 3 and 4

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#190]
All 3 stars are visible, but when I click on the hints I get this error:

![math_bot_and_inbox_ _jack_sophtron_com_and_untitled_document_-_google_docs](https://user-images.githubusercontent.com/32912678/44230133-47ea2c80-a168-11e8-8ee3-0e9f0886cdbb.gif)

**Comment by giftedprimate** [comment]
There are not videos on that level, but the user still has 3 stars.

**Comment by giftedprimate** [comment]
This will be fixed once all the videos are uploaded.

**Comment by JWWeatherman** [comment]
Closing as the other issue has links to the videos that need to be included.
