### ISSUE TITLE
Intro overview video to play on level 1

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#192]
Need to record the video and then we can figure out how to kick it off in the app.

**Comment by giftedprimate** [comment]
I think we should also have a video whenever a new concept is presented explaining the concept. The video could be played when they click the first level of a planet if they have never beat that level.

**Comment by JWWeatherman** [comment]
I just recorded this and realized that it's pretty lame. Closing this and opening a new bug for a UX person to make the video not needed.
