### ISSUE TITLE
Need to decide where and how to play the overview help video

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#193]
This is the video that can be used to help new gamers see how to navigate and use mathbot.

We need this because many people don't understand where to click to get help and where to click to get back to the profile - at least in the current UX design.

https://youtu.be/Jo0UNlSniak

**Comment by giftedprimate** [comment]
I would suggest to have it play as soon as they authenticate if they have never seen the video before. If they have seen it I would make a way to access the video from both the profile page and the game.

**Comment by JWWeatherman** [comment]
Just recorded this video and it made it really clear that we need to fix this with a more intuitive design not a video.
