### ISSUE TITLE
Recursion Level 14 map is slightly wrong

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#204]
The map doesn't provide a recurring pattern that can be solved neatly. By moving the second hook to the right one box it will.

![math_bot](https://user-images.githubusercontent.com/32912678/44314041-a9690000-a3e1-11e8-99c5-c00f7ab194ef.gif)

**Comment by giftedprimate** [comment]
@JWWeatherman 
This is the requested grid, however I beleive it will make both the bottom legs different therefor it may not have the desired effect...
![screenshot from 2018-08-20 09-19-50](https://user-images.githubusercontent.com/33336425/44342900-5aab7c80-a45a-11e8-8101-0f4f85cedb54.png)
This is the layout based on issue #173 which I think may be more suitable.
![screenshot from 2018-08-20 09-25-01](https://user-images.githubusercontent.com/33336425/44343096-fa690a80-a45a-11e8-9f57-f8d1cf4ccbc2.png)

**Comment by s3rvant** [comment]
The original layout at top of thread has neater solution as it allows 2 cycles of function which also contains maximum rocket usage:

```
function run = walk, walk
function rocket = run, run
function turn_around = turn_right, turn_right
function turn_left = turn_around, turn_right

function hook {
  turn_left
  rocket
  turn_right
  run
  turn_right
  walk
  pick_up
  turn_around
  walk
  turn_left
  run
  turn_left
  rocket
  turn_left
  rocket  
}

robot queue = walk, hook, hook, put_down, put_down
```

**Comment by JWWeatherman** [comment]
Let me know when this preprod. I’d like to play around with it a bit in this new layout as I think I can solve it cleanly now.

**Comment by giftedprimate** [comment]
With your layout from this thread or from #173

**Comment by JWWeatherman** [comment]
With the new layout.

**Comment by giftedprimate** [comment]
Ok

**Comment by giftedprimate** [comment]
@JWWeatherman this is deployed to preprod, please close this issue after you approve.

**Comment by JWWeatherman** [comment]
Verified fixed.
