### ISSUE TITLE
Add hint video to Conditonal Levels

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#205]
Level 3 hint:
https://youtu.be/7MyeHJBZvF4

Level 4 hint:
https://youtu.be/9Qnm16ny8dU

Level 7 hint:
https://youtu.be/ho-zM7OQ8bA

Level 9 hint:
https://youtu.be/FqSjGHTxuBQ

Level 14 hint:
https://youtu.be/6Pa379ZbSHo

Level 16 hint:
https://youtu.be/CAE9eMId6j4

**Comment by giftedprimate** [comment]
@JWWeatherman I will wait on this till we get issue #204 complete since it will need a new video as well.

**Comment by giftedprimate** [comment]
Deployed to pre-prod, I will let you close this issue when you confirm.

**Comment by JWWeatherman** [comment]
Verified fixed.
