### ISSUE TITLE
Find open source music for mathbot levels

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#210]
We should find a dozen or more open source music files we can use for mathbot levels. Eventually we may have our own songs created, but having a variety of songs (maybe a unique song for each level) might prove to be more fun and this is free so let's start with this.

**Comment by jordanBTCplz** [comment]
Here is the link to the song that we found for mathbot

https://drive.google.com/open?id=1lNuNRGa-dUKKeaf-koInMDp2BjQkkOu1

**Comment by jordanBTCplz** [comment]
Here is the first song that we have agreed to use for mathbot.

License Number: 490998

https://drive.google.com/open?id=1lKdiS3NQGkYmMbRjTn39VajQcpaA8Ffb

**Comment by JWWeatherman** [comment]
@NateAgapi @jordanBTCplz here is a version that simply loops for 1 hour as is (no edit):
https://drive.google.com/open?id=1Yd3oiIe13IwOXK35_2pg2Ne8976SZ-_U

**Comment by jordanBTCplz** [comment]
They both have kind of an awkward transition, so I would just go with the full version.

**Comment by giftedprimate** [comment]
I can use HTML5 to the music. Thought this might help the exploration.

**Comment by giftedprimate** [comment]
to *loop the music

**Comment by giftedprimate** [comment]
Closing this in favor of #690
