### ISSUE TITLE
Richard Porter 8/15

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#217]
This ticket is a reward request for Richard. He has been working full time on mathbot since January of 2017 (about 84 weeks). 

See closed issues assigned to Richard for details.

Richard has about 2 years of experience as a web developer and is using $60 per hour as a basis for requests.

The total requested is 202,629 (84.4 weeks * 40 * 60).

**Comment by giftedprimate** [comment]
I have receive the power ups, thanks!
