### ISSUE TITLE
Sam Axe 8/15

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#220]
This ticket is a reward request for Sam. He has provided occasional UX design help for the past few months.

Sam has about 15 years of experience as a product manager and product designer and is using $150 per hour as his 

The total requested is 2,100 (14 * 150).

**Comment by dy24703** [comment]
Please post your Indie Square Wallet address when you can Sam.

**Comment by JWWeatherman** [comment]
Sam is at burning man with all the other UX guys in the US right now :]

**Comment by jordanBTCplz** [comment]
Did we ever get Sam his tokens?

**Comment by JWWeatherman** [comment]
Closing for now.
