### ISSUE TITLE
Nate Agapi 8/15

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#221]
This ticket is a reward request for Nate. He has been working part time on mathbot since April of 2018 (about 23 weeks).

Nate has written all of the copy for mathbot.com including, but not limited to: the vision statement, outlines for the interviews JW does, and the cypherpunk manifesto. Nate paid for the "simple writing system" that he used in writing many of his pieces. The "simple writing system" was $5400. Nate has spent many hours with JW working on marketing consulting and strategy. He also sat through two of the cypherpunkU courses and did the MC for Q&A.

Nate has about 5 years of experience as a copywriter and 8 years experience in business sales and is using $150 per hour as a basis for requests.

The total requested is 51,900 (23 * 13.47 * 150). And $5,400 for copy workshop used for mathbot.

**Comment by JWWeatherman** [comment]
Please add your public address for payment and assign back to me. If something goes wrong you tokens are lost forever so I will send a test amount first. Be sure your seed words are backed up.

**Comment by NateAgapi** [comment]
1ARKvywA1hwcLiBbKxg2Bybw8ypBKbczii

**Comment by JWWeatherman** [comment]
Nate, please confirm you got the 5 test powerups and than you wrote down your seed words in a couple places and then assign back to me and I will send the remainder.

**Comment by JWWeatherman** [comment]
Excellent. Just send you the remaining 51,895. Please close this ticket when you confirm receipt.

**Comment by NateAgapi** [comment]
We're good.
