### ISSUE TITLE
Anders Kargaard

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#227]
This ticket is a reward request for Anders. He has been working part time on mathbot since May of 2018 (about 13 weeks).

Promoting on youtube, twitter, local LA meetup, networked JW onto Adam Meister to promote and Tom Woods. Produced content and had Vortex promote mathbot on Anders channel. Wrote a popular medium article about mathbot being a positive use case for mathbot (over 100 claps). 

Anders has been a founder and online marketer since 1996 and is using $150 per hour as a basis for requests.

The total requested is 12,225 (81.5 * 150).

**Comment by JWWeatherman** [comment]
Please add your public address for payment and assign back to me. If something goes wrong you tokens are lost forever so I will send a test amount first. Be sure your seed words are backed up.

**Comment by Anderskargaard** [comment]
18ui8ogw5s6NQG2v2fpzV1cr5fCwUHDJMC

**Comment by metamarcdw** [comment]
Needs moar segwit 😉

**Comment by JWWeatherman** [comment]
Counterparty doesn't support segwit. Need more RGB.

**Comment by JWWeatherman** [comment]
Anders, please confirm that you got the test 100 and that you have your seed securely written down and then assign this back to me so I can send you the remainder.

**Comment by Anderskargaard** [comment]
JW, you are not going to believe this.... just like the original mathbot sent that you did, then this didn't arrive. I am going to attach screenshot, so you can see that the address I gave you is correct and then on the same screenshot you can see that there are no Powerups. What am I doing wrong here? (The 100 Mathbot are the ones from months ago that we have now abandoned) 

![screenshot 2018-08-27 12 10 01](https://user-images.githubusercontent.com/39171116/44680438-9910e080-a9f2-11e8-8d8e-e230a9d3987a.png)

**Comment by Anderskargaard** [comment]
Hi JW, no it is the actual online Counterparty wallet. That should work fine shouldn't it?

**Comment by Anderskargaard** [comment]
You meant Indie Square right?

**Comment by Anderskargaard** [comment]
Let's try this:
1MyFcmRMdGF91avEc199fDipYFim6nVf5i

**Comment by Anderskargaard** [comment]
JW has now send the total amount.

**Comment by JWWeatherman** [comment]
Done and confirmed.
