### ISSUE TITLE
Jordan 8/15

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#233]
This ticket is a reward request for Jordan. He has been working part time on mathbot since July of 2018 (about 7 weeks).

Jordan has so far completed an edit of the "POW hardfork" paper that JW wrote, reached out to two potential interview candidates for mathbot exposure, worked out the details to get mathbot featured in Texas Homeschool Coalition's blog, is handling the token request spreadsheet, set up the marketing project board, and got the domain for cypherpunku.com set up. Jordan also incurred a $140 cost for the xenforo license. 

Jordan is using $30 per hour for reward requests.

The total requested is 530 powerups. ((30 * 13) + 140)

**Comment by JWWeatherman** [comment]
Please add your address and reassign this to me.

**Comment by dy24703** [comment]
1MZFDHvSPFfeTCnBVjiPFsgf4fQz2TEmjp

**Comment by JWWeatherman** [comment]
Jordan, please confirm you got the 5 test powerups and then assign this ticket back to me (also make sure you wrote down your seed words a in a couple places).

**Comment by jordanBTCplz** [comment]
I got the tokens and have my seed written down!

**Comment by JWWeatherman** [comment]
Excellent. Just sent the other 525. Closing ticket!
