### ISSUE TITLE
Daniel 8/15

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#234]
This ticket is a reward request for Daniel. He has been working part time on mathbot since July of 2018 (about 7 weeks).

Daniel has setup and managed JWs podcast.

Daniel is using $30 per hour for reward requests.

The total requested is 600 powerups. (30 * 20)

**Comment by damujen** [comment]
Daniel 1xDLJpU4nDeF2DuFM5gfLXrdCLJgmtLxV

**Comment by JWWeatherman** [comment]
Sent and confirmed on the blockchain :]
