### ISSUE TITLE
consider adding a more clear reset button

### ISSUE THREAD

**Issue by eth-is-a-security** [JWWeatherman/math_bot#235]
Rather than showing the reset button after it is paused it might be more clear to just have another button on screen, maybe something similar to the reload page button on a browser.

**Comment by eth-is-a-security** [comment]
This seems like it would also stop the glitch which sometimes happens where the pause and reset button disappear.

**Comment by giftedprimate** [comment]
The disappearing buttons bug was solved with issue #181.

As for the reset button, I will leave this issue open for discussion. 

Thanks!

**Comment by JWWeatherman** [comment]
I'm going to close this. We really need to be forced into adding anything additional to the screen. Ultimately we would like to add a feature that allows you to scrub forwards and backwards and change your functions in real time. I think that will address this better.
