### ISSUE TITLE
on Level 7:conditionals the left if function does not seem to identify Turquoise objects

### ISSUE THREAD

**Issue by eth-is-a-security** [JWWeatherman/math_bot#236]

**Comment by eth-is-a-security** [comment]
here are some images that might help.
![image](https://user-images.githubusercontent.com/40124613/44804838-305b6c80-ab88-11e8-859c-ae972a624d31.png)

![image](https://user-images.githubusercontent.com/40124613/44804870-42d5a600-ab88-11e8-9e8f-f0af0c97be73.png)

**Comment by giftedprimate** [comment]
Just for verification, is your left turn built?

**Comment by giftedprimate** [comment]
Actually, I just took a look at my implementation and noticed that you are missing something in your left if function.

**Comment by JWWeatherman** [comment]
Closing this. Please re-open after double-checking the video hint matches your solution.
