### ISSUE TITLE
Lions Of Liberty - get JW on their show

### ISSUE THREAD

**Issue by AndersBTC** [JWWeatherman/math_bot#238]
Approach from all angles and mention Tom Woods Performance with URL. 

Purpose is to get JW on the Lions of Liberty Show.

I approached them twice 1st and 15th of August, but without any response what so ever. Actual text and previous notes before using Github in this public Google Doc:
https://docs.google.com/document/d/1sSkcF_giNBczp4v10cHWzhDjUxy9N2DhbN9Fdyt5CKU/edit?usp=sharing

Their website: http://lionsofliberty.com/contact/

Today 23rd August I have tweeted at them including JW, Nate and the Tom Woods Video.

**Comment by JWWeatherman** [comment]
I’m scheduled to appear this Friday. 🍺
