### ISSUE TITLE
Unexplained Looping

### ISSUE THREAD

**Issue by burtwalker** [JWWeatherman/math_bot#242]
My 13 year old grandson is doing some testing. He encountered this problem near the end of the Recursion planet. There appears to be an infinite loop without making a recursive call.  I logged into his account and discovered that he had accidentally removed the steps in the U-Turn function. After adding the proper steps back to the U-Turn function, it began to behave properly. 

I was able to duplicate the activity by removing the steps in the U-Turn function again, dragging the Comb function out of the timeline and adding it back.  Obviously, he shouldn't have done this, but it's likely to occur with kids in the future.  Maybe disallow empty functions?

I couldn't upload the video, so here's a link to view it:
https://drive.google.com/open?id=1PUAoiZStbbbkthgjGj9Kvf4L1JF_Mm9I

![math_bot-1](https://user-images.githubusercontent.com/728077/44591749-885f3100-a78c-11e8-9bda-519a330e4763.png)

![math_bot](https://user-images.githubusercontent.com/728077/44591731-81382300-a78c-11e8-8037-a0fd43c6f288.png)

**Comment by JWWeatherman** [comment]
Hey Burt, is this still happening? I can't get it to repeat. Also, it looks like your u-turn function is empty. It should have two right turns inside it.

**Comment by giftedprimate** [comment]
Closing this since this issue is being dealt with in other issues.
