### ISSUE TITLE
Get overview of Texas Homeschooling Coalition Advertising Policy

### ISSUE THREAD

**Issue by NateAgapi** [JWWeatherman/math_bot#248]
Hey Jordan, can you talk to your contact at THSC and figure out what kind of advertising they accept both online and in print. If you could get stats on web traffic and how many physical magazines they ship every quarter, that would be very helpful. Also give me a run down on the various formats. And of course pricing. Then just put that summery into a google doc and link it here. 

Thanks.

**Comment by NateAgapi** [comment]
Both online and in print.

**Comment by jordanBTCplz** [comment]
Hey I just updated the document with some new info. if you don't need any additional info; go ahead and close this issue.

**Comment by NateAgapi** [comment]
Thanks Jordan.
