### ISSUE TITLE
Get JW on Breaking Math Podcast

### ISSUE THREAD

**Issue by AndersBTC** [JWWeatherman/math_bot#257]
Seems they have 1600+ subscriber according to my podcast player. 
http://breakingmathpodcast.com/ 

Get JW on their show.

Use Tom Woods show as reference: https://youtu.be/-fpiCJCeE48

Link to JW YouTube channel: https://www.youtube.com/channel/UCkaB2u7zG4uSCL5Hws3X1jw 

Use JW and Nate as well and potentially namedrop Cody Wilson and Lyn Ulbricht.

8/28/2018: E-mailed on breakingmathpodcast@gmail.com with JW cc:.

**Comment by AndersBTC** [comment]
9/12/2018
Still didn't hear back to followed up with this e-mail, JW cc::

Hi Breaking Math

 I really think that ex-college professor and Mathbot.com Founder JW would be a great guest on your show. He was recently on Tom Woods' show https://youtu.be/-fpiCJCeE48 (worth a 30 second listen) and is on his way to the Owen Benjamin show as well as Lions of Liberty. 

I think you will find it valuable for your audience as https://mathbot.com revolutionizes math learning as it for the first time combines gamification with incentivization paid by parents, grand parents or anyone really. Plus anyone playing learns programming which is increasingly important in today's job market. 

JW is an amazing speaker and guest. I would love to hear back from you, if you would like to have him on as a guest?

**Comment by AndersBTC** [comment]
And Gabe replied back on my follow up and sounds very positive and would love to speak with me about JW and Mathbot. I am trying to get JW to maybe take the call as he can probably convince him even better.. otherwise I am totally down for it!

**Comment by AndersBTC** [comment]
9/13/2018

Had a great talk with Gabe and he is willing to take JW on the podcast. Here is the summery as also written to  JW in e-mail, as he now has to plot the time for the recording with them:

Hey JW

We've got another JACKPOT!

This is right in the math loving target group with teachers in their listeners, so your appearance here already is bound to bring strong rings in the water with teachers potentially introducing Mathbot to many students.

There are a few conditions, but I think that you are quite alright with these:
1) The two hosts work Monday-Friday 9-17 so it needs to be taped in evening or weekend. As I recall you actually work Sundays and you seem to be always working evenings 

2) On their podcast team some members are positive to common core and among their listeners it's the same. So the focus should be strictly on all the positives of Mathbot and learning the way that Mathbot enables, without negative critique on common core. I am pretty sure that this will always have to be the angle on math shows, while the anti-government anti-common core is the way to go on liberty and homeschooling podcasts
Plenty positives can be said about the incentivization without talking common core
Same goes with the fact that the kids will learn programming as well, which is increasingly important
And I think it is a great point that we want to elevate math education globally by making all levels free to play and that we beleive that it will help solve a lot of real problems in society

3) They like to make their guest shine and be super interesting, so he would like you to submit questions that they can ask you like "what was/is your favorite math problem" and "what was/is your favorite programming challenge" and other questions that can make you stand out like a person it will be really interesting for the crowd to listen to. Don't worry that will  be easy for you!

So his name is Gabe/Gabriel Hesch, their website is http://breakingmathpodcast.com/, his number is: 5057103717  and his e-mail is breakingmathpodcast@gmail.com

So now it is in your hands to contact him to confirm 1) no common core negative 2) questions to yourself 3) finding a time for the recording.

I think that is it right?

**Comment by JWWeatherman** [comment]
Spoke with these guys and they are struggling since they have a bunch of fans of common core, but the episode after we spoke had a math teach on and they hammered him about Euclid so I think they have been impacted already :]

**Comment by JWWeatherman** [comment]
Sent another nag email just now.

**Comment by AndersBTC** [comment]
Alright, I hope something comes out of it..

-------------------------------------------------------------------------------------
Learn math by programming a robot on https://mathbot.com - soon you can
incentivize with Bitcoin. The open source project appreciates any help, if
you find any bugs then this video teaches you how to report the issue:
https://youtu.be/FH1xXdo_FFU


If you have worked with me I would greatly appreciate a review on the below
three media. If you consider working with me, you can read what other
people say:

Google:
https://goo.gl/LlEKXR

Yelp:
https://www.yelp.com/biz/la-online-group-los-angeles-2

Facebook:
https://www.facebook.com/pg/LAOnlineGroup/reviews/?ref=page_internal
<https://www.facebook.com/LAOnlineGroup/>

*On a mission to grow your business!*


Kind regards
Anders Kargaard

Owner | Strategic Media Thinker
LA Online Group

*Google AdWords - YouTube - Conversion Optimization *

www.laonlinegroup.com
(424) 421-9975

**Comment by JWWeatherman** [comment]
Did the podcast. Should be published soon. Good job Anders.
