### ISSUE TITLE
Record new video for Recursion Level 14

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#280]
Level has been updated

**Comment by JWWeatherman** [comment]
Ready to deploy. 

The first hint is:
https://youtu.be/Y8DCXlnBhRo

The last hint is:
https://youtu.be/CntzuVR13mM

**Comment by giftedprimate** [comment]
Deployed to pre-prod, I will let you close this issue after you confirm.

**Comment by JWWeatherman** [comment]
verified fixed preprod.
