### ISSUE TITLE
New function won't drop on chrome using a mac (premathbot)

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#284]
https://drive.google.com/file/d/1X_-Mjo15bHzNNPedcqZUQJ7HpRiG9DFL/view?usp=sharing

**Comment by JWWeatherman** [comment]
We should make it so that if the new function is dropped anywhere outside the black box it moves into the staged functions area.

**Comment by giftedprimate** [comment]
Done.

**Comment by giftedprimate** [comment]
Deployed to pre-prod, I will let you close this issue after you confirm.

**Comment by JWWeatherman** [comment]
Right now you have to drag the new function down to roughly the right area. We should make it so that if you drag and drop anywhere outside this box it works - even if you drag it up. But this is more a feature request than a bug now.

**Comment by giftedprimate** [comment]
@JWWeatherman This is a pretty complicated task (is definitely doable) so I would like to tackle it after authentication is complete.

**Comment by giftedprimate** [comment]
@JWWeatherman deployed to preprod, ready for inspection.

**Comment by giftedprimate** [comment]
Deployed to prod, leaving open so JW can inspect at a later time.

**Comment by JWWeatherman** [comment]
Perfect.
