### ISSUE TITLE
Depending on how you enter the next planet button it might not be clickable

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#285]
The video is attached. When the cursor is not a hand the button is unclickable - I am clicking when it is still for a few seconds.

https://drive.google.com/file/d/1UDffm8oc3cnnlvBKA3XPlWpAPvjT6vU5/view?usp=sharing

**Comment by giftedprimate** [comment]
I can't reproduce this bug.

**Comment by giftedprimate** [comment]
I tested this on mac and linux and am unable to recreate the bug.

**Comment by giftedprimate** [comment]
I just recreated it, this is easy to fix.

**Comment by JWWeatherman** [comment]
Verified on preprod.
