### ISSUE TITLE
Stars are not resizing correctly

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#286]
On any level:

1. Make the window small and then very big. Notice that the stars get big and don't shrink back down.
2. Hit refresh and notice that the stars get resized correctly.

This has been repo'd on mac using Chrome.

**Comment by JWWeatherman** [comment]
![math_bot](https://user-images.githubusercontent.com/32912678/44999376-c4637480-af8a-11e8-8eb8-35e6a105689b.gif)

**Comment by giftedprimate** [comment]
This is a result of the firefox optimization and should be easy to fix.

**Comment by giftedprimate** [comment]
Done

**Comment by giftedprimate** [comment]
Deployed to pre-prod, I will let you close this issue after you confirm.

**Comment by JWWeatherman** [comment]
Verified fixed on preprod.
