### ISSUE TITLE
Free (and mandatory) Hints Feature

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#290]
To help people know how to navigate the site and use the hints feature I want to play these videos automatically at the start of each level. 

If we can't find a "dev art" way to do this we can ask Sam for a design when he returns from Burning Man in a few days (so just assign it back to me).

Planet 1, Level 1
https://youtu.be/q9V-TnU-0Yw

Planet, Level 2
https://youtu.be/RUxCBeJx-Bg

Planet 1, Level 4
https://youtu.be/WBMNlpX_VqE

If we can find a nice user experience we can put more free hints into the game, but I think we will always need to force the users to listen to the video that explains that some of the levels are impossible to beat without a hint and that there is no shame in it or extra points for learning the hard way.

**Comment by giftedprimate** [comment]
Since we are going to make the background black for the other videos I will make this video play the same way.

**Comment by giftedprimate** [comment]
@JWWeatherman  Implementation deployed to pre prod, ready for inspection.

**Comment by JWWeatherman** [comment]
This is amazingly cool. That's going to help a lot with gamer training.

**Comment by giftedprimate** [comment]
Deployed to prod.
