### ISSUE TITLE
Replace the countdown timer with an animated stripes progress bar

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#291]
Instead of a timer below the button let's add a progress bar on the button, under the stars.

I think this will be more intuative and look nicer. Some people though the countdown was telling them that they only had a certain amount of time to pass the level :>

I like the animated stripes one at the bottom of this, but you can use whatever of course.
https://getbootstrap.com/docs/4.1/components/progress/

**Comment by giftedprimate** [comment]
Vue js has a really nice way of doing this.

**Comment by giftedprimate** [comment]
@JWWeatherman merged to master (#318) and deployed to pre-prod, ready for inspection.

**Comment by JWWeatherman** [comment]
Verified fixed.

**Comment by giftedprimate** [comment]
Closing because tweaks to this issue are being address in #304
