### ISSUE TITLE
Blocked out squares image does not resize with the screen

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#302]
On chrome on a mac and also on firefox on a mac.

You can see in this image that only two lines are visible on each square, but if you make it larger you will see more lines. I think this is because the background image is not resizing correctly with the rest of the screen.

<img width="634" alt="tmp" src="https://user-images.githubusercontent.com/32912678/45114952-66669680-b11c-11e8-8721-211924411d43.png">

**Comment by giftedprimate** [comment]
@JWWeatherman I had some time for an easy win this evening so I knocked this one out. Deployed to pre-prod, ready for inspection.

**Comment by giftedprimate** [comment]
Deployed to prod, leaving open so JW can inspect at a later time.

**Comment by JWWeatherman** [comment]
Looks great now.
