### ISSUE TITLE
Remove the speech buble

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#304]
I think we might not need it now that we have automatic hint videos. And we should test this by pulling it and seeing how it works.

**Comment by giftedprimate** [comment]
@JWWeatherman Deployed to preprod, ready for inspection.

**Comment by JWWeatherman** [comment]
It looks a little empty now. Let's:

1. bring back the robot (no speech bubble).
2. shrink the profile image (awesome that it grabs it from google if its available) and move it out to the right corner (have the right side of the circle right align with the play button.
3. Put the stars on the right side.

<img width="1159" alt="tmp" src="https://user-images.githubusercontent.com/32912678/45258140-c2c9f000-b380-11e8-841a-86502dc856e0.png">

**Comment by JWWeatherman** [comment]
Let's also make the progress bar and the stars direction align.

1. Progress bar grows from the left to the right.
2. Stars are removed from the right to the left.

Ideally we would combine the two so that the stars look like they are being refilled from left to right and after the progress bar fills a star it turns yellow again and the next star begins to be refilled, but I think the above will make it make sense visually.

**Comment by giftedprimate** [comment]
@JWWeatherman These changes are deployed to preprod and are ready for inspection.

**Comment by JWWeatherman** [comment]
Looks awesome. Verified on preproduction.

**Comment by giftedprimate** [comment]
Deployed to prod
