### ISSUE TITLE
Get JW on Peaceful Anarchism

### ISSUE THREAD

**Issue by AndersBTC** [JWWeatherman/math_bot#308]
Use Tom Woods' show as reference: https://youtu.be/-fpiCJCeE48

Namedrop Cody Wilson and Lyn Ulbricht.

Mention JW as fast rising Bitcoin Influenser and Ancap.

Mention who we are:
https://twitter.com/JWWeatherman_
https://twitter.com/Anders_
https://twitter.com/NateAgapi

9/7/2018: So their contact form did not work on the website so asked Shane from @LUAradio for intro or contact info and he said he would just send Danilo a DM on FB.

**Comment by LUA2018** [comment]
9/7/2018: Reached out to Danilo via a FB message.
--------------------------
Hey Danilo!
I hope all is well, man.

I wanted to recommend someone who I think would be a terrific guest for your podcast. His name is JW Weatherman. He's a software security expert, Bitcoin maximalist, ex-college professor, an-cap, and the founder of MathBot.com, a game that teaches kids math by programming a robot.

The ultimate objective for the project is to put public school teachers out on the street with "job needed" signs.

I know ya'll would have a terrific chat and your homeschooling/unschooling audience would greatly benefit from MathBot!

Check out his recent appearance on the Tom Woods show -- I know you'll dig it! https://youtu.be/-fpiCJCeE48

If you're interested, you can reach out to him on Twitter, @JWWeatherman_ or you can respond to me and I'd be happy to help set it up!

Thanks, man!
-Shane
