### ISSUE TITLE
Recursion Level 6, only "left" function available

### ISSUE THREAD

**Issue by AndersBTC** [JWWeatherman/math_bot#311]
Only the function for making a left turn is available. I got through with a work around by using the left turn as the function itself that I needed (stair), but it seems intuitively wrong that it is not an "open" programmable function available instead of the left turn function with the left arrow on it. 

OK, it seems that the stair function might have been there first, but that it dissapeards, if I leave the level and come back, as this happened to me at the next level. 

![screenshot 2018-09-07 16 22 53](https://user-images.githubusercontent.com/39171116/45247207-05c19000-b2bb-11e8-8654-ec74384826c7.png)

**Comment by AndersBTC** [comment]
OK, it seems that the stair function might have been there first, but that it dissapeards, if I leave the level and come back, as this happened to me at the next level.

**Comment by AndersBTC** [comment]
Yes at level 5 the + button to add new functions is there, but it is missing on level 6. Thanks.

**Comment by giftedprimate** [comment]
@AndersBTC Ok cool, there's a function in level five called stairs you need to add in order to beat this level.  

I am going to write some code sooner or later to deal with this issue. 

Thanks!

**Comment by AndersBTC** [comment]
Thanks! Yeah I guess I must have messed up somehow, by not adding but just using another function, which then left me missing the stairs on level 6. 

I guess it should not be possible to make the mistake that I did.. ;-)

**Comment by giftedprimate** [comment]
Closing issue since this is permanently resolved by issue #370
