### ISSUE TITLE
Create podcast/radio advertisement for Mathbot.

### ISSUE THREAD

**Issue by LUA2018** [JWWeatherman/math_bot#314]
It would be a good idea to create a 30/60 second podcast/radio advertisement for MathBot. I know quite a few folks who would run it for free.

I can take care of this sometime in the near future, unless someone else beats me to the punch.

Script:
TBD

**Comment by NateAgapi** [comment]
We already have an issue for this that I'm working on. I'm working on one for the Tom Woods show.

**Comment by LUA2018** [comment]
Understood, thanks Nate. Must have missed that. My apologies!
