### ISSUE TITLE
Highlight current level on profile page

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#323]
Let's add a feature to highlight your current planet and level when you click on the profile page. Currently the only way to figure it out is to click back and forth a few times guessing (assuming you have past a few levels ahead).

**Comment by giftedprimate** [comment]
@JWWeatherman Feature is implemented and deployed to preprod, ready for inspection.

**Comment by JWWeatherman** [comment]
This is a very elegant solution. It still makes it hard to know what level you are currently playing if you hop between planets, but I'm not sure that is a problem worth solving with a more cluttered UI so I am going to close this for now. Great fix.

**Comment by giftedprimate** [comment]
@JWWeatherman Not sure if you noticed but the selected level also always scrolls to the same position when you go the the profile page.
