### ISSUE TITLE
Make it easy to share Mathbot.com through Facebook, Twitter, e-mail etc. 

### ISSUE THREAD

**Issue by AndersBTC** [JWWeatherman/math_bot#324]
I am happy with the organic growth we have, but think we can do much better. 

I realized that we miss one important function to "get the snowball rolling down the mountain", which is my go-to term for "word of mouth". Anytime you have a good enough product, then success often is a matter of momentum itself, provided quality execution is in place. Once the snowball has momentum, nothing can stop it from picking up more snow.

We need to make it super easy for people to share their knowledge of or experience with Mathbot.com. So my simple (and far from original idea, since most websites use this) is:

1) From the homepage have those buttons where people can easily click and then be taken to a default message on that particular social media to catalyze word of mouth. I think the most important are FB, Twitter, e-mail and then there are probably are few others.

2) Again these buttons should probably be located in the footer/header on every single page, as they help the word of mouth effect. I am in particular also thinking on the page of each "You Won" page, where it is very nice for a kid (or someone else) to be able to send that message to family/friends that "Hey I passed Recursion level 6/15". On these "You Won" pages the correct location in my opinion is not only in the footer, but right under that "You Won" message, and I think it is important that it is tailored to the exact level they reached. That message might be even more creative than what I suggested, but maybe people will take care of that themselves.

**Comment by LUA2018** [comment]
Great idea. I can dig it.

**Comment by giftedprimate** [comment]
@AndersBTC @JWWeatherman social button are added on both the about and profile footers as well as in the win sequence.

Deployed to pre-prod, ready for inspection.

**Comment by AndersBTC** [comment]
Hey Richard. I am still new to the "software development" part of Github. I tried clicking through to to inspect it in Development, but I can't actually see the graphics, when I click on it on there. 

Can you please give me a "how to" for dummies to get to your work, so I can see it?

**Comment by giftedprimate** [comment]
Deployed to prod, leaving open so JW can inspect at a later time.

**Comment by AndersBTC** [comment]
I would on the homepage suggest that a title to the social media buttons is introduced as "Tell Your Friends", but will leave this for our designer to decide. But if there is no call to action, it probably won't have the desired effect. 

Unfortunately I can't see the "You Won" screen on https://premathbot.com/robot. The spaceship just keeps flying around the spiral, but doesn't actually take me to the first game. But again I would say that the important thing here is a call to action such as:
"You won, let your friends know about your success by sharing with them through one of the below social media buttons."

I am just realizing that Instagram probably is the biggest social media among kids, so maybe it is possible to program an Instagram share button with a link back to mathbot.com for the people who see it.

**Comment by giftedprimate** [comment]
@AndersBTC you must have checked it out while I had a jacked up version deployed today, it is fixed now. 

I'll add the instagram link tonight.

**Comment by giftedprimate** [comment]
@AndersBTC  It looks like Instagram doesn't have a link for social links.

**Comment by AndersBTC** [comment]
Hey Richard, it really looks great man, thanks for implementing! I LOVE the possibility to social share after beating a level, I think that kids will really use this to show to friends and family. Great way to onboard new users! 

In general it's really great to see how Mathbot changes and improves almost every other time I visit the website. Great job guys!

**Comment by JWWeatherman** [comment]
I think this looks good. The only thing I would like to change is to have nate write the tweets, etc so I am going to assign this to him.

Nate, just put the text you would like posted for each of the social platforms here and assign it to Richard.

**Comment by NateAgapi** [comment]
Here's a tweet: I just found this cool site: https://mathbot.com. It's a fun little game, but I guess it teaches you programming & math too. I'm enjoying it. It's very satisfying when you get that little robot to finally bend to your will! **World Domination Face**

What about Facebook? I don't use that anymore. Is there any copy needed for that?

**Comment by NateAgapi** [comment]
Damn Github and it's automarkup. So "World Domination Face" should be preceded by ** and followed by **.

**Comment by giftedprimate** [comment]
@NateAgapi I can do Facebook.

**Comment by giftedprimate** [comment]
@NateAgapi The platforms are the following...

- linkedin
- facebook
- twitter
- reddit

**Comment by giftedprimate** [comment]
@NateAgapi I think the Tweet you already wrote will work fine for all the platforms (and it makes coding this allot simpler), what do you think @JWWeatherman?

**Comment by NateAgapi** [comment]
Yeah, you can just take that copy, Richard, and use it on the other platforms.

**Comment by NateAgapi** [comment]
I just talked to JW about this now, and he agrees with you, so you're good to go Richard.

**Comment by giftedprimate** [comment]
@NateAgapi I have these hashtags included as well for Twitter...

- mathbot
- math_bot
- math
- programming
- jwweatherman_

Do you think that is sufficient?

**Comment by NateAgapi** [comment]
No, hashtags make for awful copy. Just keep it the way I wrote it. The point is to have the copy sound organic to the person who tweets it. The hashtags make it look like spam. Plus, they don't accomplish anything anyway. They are really only good when a hashtag makes it in the trending list. Even then, I wouldn't use them in copy as people tend to not read tweets with a lot of hashtags.

**Comment by giftedprimate** [comment]
I'm a social media agnostic! Good to know, thanks!

**Comment by giftedprimate** [comment]
@JWWeatherman Nate's Tweet is implemented on preprod.

**Comment by JWWeatherman** [comment]
Looks great.

**Comment by JWWeatherman** [comment]
Hey Richard,

When you get a chance can you make the copy exactly this. There is some weird formatting and my twitter handle in the current version.

I just found this cool site mathbot.com. It's a fun little game, but I guess it teaches you programming & math too. I'm enjoying it. It's very satisfying when you get that little robot to finally bend to your will! **World Domination Face**

**Comment by giftedprimate** [comment]
@JWWeatherman always something! I'll get to it in a minute. As for the formatting, there's not much I can do with it other than put it in the text box.

**Comment by JWWeatherman** [comment]
Cool. And can you change each color of the letters so that they make a rainbow? And make the colors reverse after every 20th character. And flash :]

Here it is now:
        I just found this cool site: https://mathbot.com. It's a fun little game, but I guess it teaches you programming & math too. I'm enjoying it. It's very satisfying when you get that little robot to finally bend to your will! **World Domination Face**
       https://mathbot.com via @JWWeatherman_

And here is what we want:
I just found this cool site mathbot.com. It's a fun little game, but I guess it teaches you programming & math too. I'm enjoying it. It's very satisfying when you get that little robot to finally bend to your will! **World Domination Face**

So there are some extra spaces before "I just found out" and the last line should be nuked.

**Comment by JWWeatherman** [comment]
Pft. When I paste it into github it removes the extra spaces before "I just found out"

**Comment by giftedprimate** [comment]
I literally don't have control over the spaces in the beginning. I  just send the text to the url and it is placed in the box for me.

**Comment by giftedprimate** [comment]
@JWWeatherman The fix is deployed to production. :)

**Comment by NateAgapi** [comment]
Richard, I just want to give you a reminder that the copy should read: "I just found this cool site mathbot.com. It's a fun little game, but I guess it teaches you programming & math too. I'm enjoying it. It's very satisfying when you get that little robot to finally bend to your will! ** World Domination Face **"
But make sure to delete the space between the asterisks and "World Domination Face." Github automatically marks that up as bolded font. We want the asterisks included in the copy.

**Comment by giftedprimate** [comment]
@NateAgapi Already done and deployed to prod.
