### ISSUE TITLE
Conditionals Level 6, I Pass Even Though I Incorrectly Carry 3 Kittens

### ISSUE THREAD

**Issue by AndersBTC** [JWWeatherman/math_bot#329]
I am not 100% sure that this is an error, but it seems that it is, since the portal is not "asking" for 3 kittens. At the same time because of my "Walk Turn" function I actually do pick up the three kittens as you can see on the screenshot. 

I passed the level despite bringing these three kittens to the portal that probably shouldn't be there. 

![screenshot 2018-09-11 12 45 10](https://user-images.githubusercontent.com/39171116/45386160-7a504380-b5c7-11e8-8d47-484a44102fd3.png)

**Comment by giftedprimate** [comment]
@AndersBTC The goal of this level is just to get to the portal. 

Good job!

**Comment by AndersBTC** [comment]
Yeah I figured afterwards that it was "okay" to carry three kittens unnecessarily to the portal, but it just felt wrong and like I was cheating the game. But I will leave it here. You can close the issue if you want ;-)

**Comment by giftedprimate** [comment]
@AndersBTC Cool, I'll leave it open in case @JWWeatherman wants to chime in. He's the level designer.

**Comment by JWWeatherman** [comment]
Yeah, when the portal doesn't have a number the goal is just to get to it by any means possible with anything in your hands.
