### ISSUE TITLE
If I Pause the Game (because I see mistake) Then I Can't "Restart" Without Refresh of the Page

### ISSUE THREAD

**Issue by AndersBTC** [JWWeatherman/math_bot#336]
This happens if I play a level and I see that I programmed it wrong half way through the game. I stop it or pause it, to correct my error and restart, but I am not given the chance to restart and none of the buttons work for me  to restart. I have to refresh the page to give the level another try.

It seems that this issue is avoided, if I let the robot go all the way to the end and realize that the level is failed.

![screenshot 2018-09-12 14 51 09](https://user-images.githubusercontent.com/39171116/45455390-c40a5e00-b69b-11e8-9bb5-036f93f97afe.png)

**Comment by giftedprimate** [comment]
@AndersBTC looking into it now.

**Comment by giftedprimate** [comment]
@AndersBTC I'm having some trouble recreating this bug. I will keep this issue open since I'm sure to notice it as I work on other things.

**Comment by JWWeatherman** [comment]
I am going to close this as no-repo even though its probably an issue still. Hopefully we will get a solid repo soon.
