### ISSUE TITLE
Level 7 world 5: conditionals do not work unless both slots are used in the function.

### ISSUE THREAD

**Issue by eth-is-a-security** [JWWeatherman/math_bot#344]
![image](https://user-images.githubusercontent.com/40124613/45580955-b0f2bc00-b85c-11e8-9de3-96a4501cc504.png)

![image](https://user-images.githubusercontent.com/40124613/45580968-c667e600-b85c-11e8-8d5c-6d546648f092.png)

![image](https://user-images.githubusercontent.com/40124613/45580996-0929be00-b85d-11e8-9b06-91a41e637b26.png)

**Comment by JWWeatherman** [comment]
@giftedprimate I think this is a good bug.

**Comment by giftedprimate** [comment]
@JWWeatherman I need to whiteboard this one out to make sure this is not actually a bug with the compiler.

**Comment by giftedprimate** [comment]
@eth-is-a-security @JWWeatherman  The robot must drop the block so that he is not holding it after the recursive functions is called again. Conditionals refer to if the robot is holding the color.

Hope this helps! I'm going to close this issue for now since this is by design.
