### ISSUE TITLE
Richard Compensation Request 9/16

### ISSUE THREAD

**Issue by jordanBTCplz** [JWWeatherman/math_bot#357]
Richard, please post your reward request and a brief explanation of the tasks completed. When finished please paste in your Indie Square wallet address that you want your tokens sent to and assign this issue to JW.

**Comment by giftedprimate** [comment]
Powerups requested - 
    - 165 hours worked * 60 hr = 9,900

Address -
   1JsEHmaff94Pn88esmuTrc4CKBjJXifSnJ

Description - Solves multiple issues related to improving user experience. Implements authentication front end. Handles all devops for both the pre production site and the production site.

**Comment by giftedprimate** [comment]
Got em, thanks!
