### ISSUE TITLE
Anders Compensation Request 9/16

### ISSUE THREAD

**Issue by jordanBTCplz** [JWWeatherman/math_bot#358]
Anders, please post your reward request and a brief explanation of the tasks completed. When finished please paste in your Indie Square wallet address that you want your tokens sent to and assign this issue to JW.

**Comment by AndersBTC** [comment]
47.5 hours of 150/hour = 7,125

18ui8ogw5s6NQG2v2fpzV1cr5fCwUHDJMC

Worked on getting JW on podcasts and YouTube shows. Several "success" cases or people that responded back that they are up for it: Breaking Math, Eric July (on JWs channel as guest), helping close Owen Benjamin through Superchat, a mum with a homeschooling podcast that I forgot the name of, plus I think one more.

Explained to Shane how Github works and got him started using it for all the many liberty podcasts that he knows. 

Reported some bugs.

Suggested some features.

**Comment by AndersBTC** [comment]
You got it, thanks!
