### ISSUE TITLE
Shane Compensation Request 9/16

### ISSUE THREAD

**Issue by jordanBTCplz** [JWWeatherman/math_bot#359]
Shane, please post your reward request and a brief explanation of the tasks completed. When finished please paste in your Indie Square wallet address that you want your tokens sent to and assign this issue to JW.

**Comment by LUA2018** [comment]
![image](https://user-images.githubusercontent.com/34818848/45598650-1baf0f00-b9a5-11e8-9bb1-fff8bd8643ff.png)

4.5 hours for this month so far. As far as the Indie Square wallet address, I don't think I have access to that. I have a Counterparty wallet, but haven't gotten information on what to do next.

**Comment by NateAgapi** [comment]
Indie Square is a phone app we use to generate our seeds. It should be on both iphone and Android.

**Comment by AndersBTC** [comment]
Hi Shane. So you also take into account the amount per hour of $20, which we spoke about, so your request in this case would be 90 tokens.

**Comment by LUA2018** [comment]
1BDtdbuL44dXnStE782Nkippx9PawfEzhs is my Indie Square address. 90 tokens I suppose. Thanks for the help, guys.

**Comment by JWWeatherman** [comment]
Just sent. Please confirm you get em and then close this issue :]

**Comment by LUA2018** [comment]
Got them! Thanks.
