### ISSUE TITLE
All generated functions should be available for each level

### ISSUE THREAD

**Issue by giftedprimate** [JWWeatherman/math_bot#370]
If a user is able to pass a level without using a generated staged function and said function is needed in a later level, program should generated function at that point.

**Comment by giftedprimate** [comment]
@JWWeatherman all needed functions will be available even if the user did not use it on an earlier level. Deployed to pre-prod, ready for inspection. I also made some improvements to the UI.

**Comment by giftedprimate** [comment]
Deployed to prod, leaving open so JW can inspect at a later time.

**Comment by JWWeatherman** [comment]
I'm going to close this even though I didn't have time to play through the levels to try to pass a few without the expected functions and then see if they are automatically added as needed.
