### ISSUE TITLE
Adding operation names in "panel" (Green Line)

### ISSUE THREAD

**Issue by codeShark149** [JWWeatherman/math_bot#41]
1.	Including the name of the operation below each one of them in the control panel (Where kids will create the sequence) will increase the visibility of the sequence created. This will make it easier to go through the steps and cross check if they have entered what they have actually thought. 
![issue 1](https://user-images.githubusercontent.com/36541669/40653927-516006f0-635a-11e8-930a-defd5f78f156.PNG)

**Comment by JWWeatherman** [comment]
This is a tough one. Going to leave open, but the UX designer was trying to find a good balance between usable and pretty.

**Comment by smh69** [comment]
can confirm, that similar to when editing function contents, that in production, hovering over something in main shows a tooltip; very useful.

**Comment by giftedprimate** [comment]
Closing this for now since the overall design has diverged quite allot.
