### ISSUE TITLE
More video suggestions are back on youtube

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#410]
We don't want additional video suggestions to show up on youtube. We had a setting someplace that made this go away, but it looks like they are back. 
<img width="907" alt="screen shot 2018-10-10 at 10 54 50 am" src="https://user-images.githubusercontent.com/32912678/46745448-0f079900-cc7b-11e8-98f7-4c7941d6858e.png">

**Comment by giftedprimate** [comment]
@JWWeatherman Fixed and deployed to preprod.

**Comment by JWWeatherman** [comment]
perfect
