### ISSUE TITLE
Need a sandbox to experiment with additional problems

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#416]
Let's use this layout. For now just put the objects we already have, but as we add additional objects we will put them in these locations. Also, no need for a portal in the sandbox, but this can be the default location of the portal for math levels.

Marking this a P1 just because I know we are going to do this right now, but if it turns out to be difficult we can decrease the priority.

<img width="706" alt="math_bot" src="https://user-images.githubusercontent.com/32912678/46767207-48a7c680-ccb2-11e8-9983-f07dfe33f89e.png">

**Comment by giftedprimate** [comment]
@JWWeatherman It is deployed to pre-prod. 

To access...

1) Signun
2) From profile page 
    - ctl + alt + s

**Comment by giftedprimate** [comment]
Keyboard shortcut is now ctl + space

**Comment by JWWeatherman** [comment]
Go to profile page and click ctl + space to access the sandbox.
