### ISSUE TITLE
Fixing the justification of code sequence in the "panel"

### ISSUE THREAD

**Issue by codeShark149** [JWWeatherman/math_bot#42]
2.	While adding operations into the panel, the present behavior is the left most and right most elements move in order to keep the whole sequence justified in the panel. This creates a difficult situation when the sequence becomes larger than the length of the panel, where after putting the last operation it doesn’t become immediately clear where is the operation placed as the list again tries to justify itself. My suggestion is, keep the latest added operation at the center or may be up to 75% of the panel length. Then keeping the right most position fixed, push the previous operations to left as required. This can making adding operations into the panel clearer. 
![issue2](https://user-images.githubusercontent.com/36541669/40654000-9a4944b2-635a-11e8-8754-22a864ae0492.PNG)

**Comment by JWWeatherman** [comment]
This is a great idea. Might be a little tricky, but Richard has some ideas of how we can make this better.

**Comment by giftedprimate** [comment]
@codeShark149 I was able to implement this. Now if  the quantity of functions exceeds 50% of the drop zone the dropped function will center itself.
