### ISSUE TITLE
Need to simplify  the new signup screen

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#423]
Let's remove the "link to image" and "name" fields. I get that we get those automatically when they sign up with google, but let's just use a standard string "NoName32" if it's a required field in the DB (or something smarter is fine too) since we don't actually use it in the app. It is nice to have when we send email, but it's not worth the spike on the signup flow.

For image we should just use a default and then allow them to upload an image, but that can be a low priority feature.

<img width="360" alt="screen shot 2018-10-11 at 11 16 53 am" src="https://user-images.githubusercontent.com/32912678/46814933-cbc72c00-cd47-11e8-8011-b5a08df8ccbb.png">

**Comment by giftedprimate** [comment]
@JWWeatherman deployed to preprod.

**Comment by JWWeatherman** [comment]
Perfect.
