### ISSUE TITLE
Adding Double Click option along with Drag/Drop

### ISSUE THREAD

**Issue by codeShark149** [JWWeatherman/math_bot#43]
3.	As in the case for large sequence of Opps, along with Drag-Drop operation, using double click to add/remove Opps into the panel can make the experience cleaner. Having Drag/Drop can be fun for the kids at the start, but letter the site should reveal that they can do it too with Double Click, this will make the addition and removal of operation crisper. ****

**Comment by JWWeatherman** [comment]
Double click doesnt exist on mobile and we are trying to maintain a unified experience. Good idea though - we actually tried this a while back.
