### ISSUE TITLE
Extra kitty created 

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#435]
In the attached video I show that there should be one kitty held by the robot and none on the square, but we end up with one on the square and held by the robot.

https://drive.google.com/file/d/1X0lm3lHrjvdeG-T9DuCbWPAdsIHY4aFg/view?usp=sharing

**Comment by giftedprimate** [comment]
@JWWeatherman This bug has been inadvertently solved at some point, below is a video of the app working fine. This is deployed to pre-prod.

https://drive.google.com/file/d/1HouaCFhA0sjk4V92V7G2kNZdU1RGaJoh/view?usp=sharing

**Comment by JWWeatherman** [comment]
Awesome.
