### ISSUE TITLE
Text and image toggle

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#436]
I think I found a good way to support more icons using custom text without adding additional UI elements. 

When the user clicks on the icon (when editing the function) the icon toggles between being the name of the function and the icon/image.

I've been getting confused now that I'm working with a couple dozen functions and I think this will help a lot.

https://drive.google.com/file/d/1iAkzyYsYd0GwCS3_637mnqadlQ312Uv2/view?usp=sharing

**Comment by giftedprimate** [comment]
@JWWeatherman This is implemented in preprod.

**Comment by JWWeatherman** [comment]
Two excellent features in 24 hours. Very cool.
