### ISSUE TITLE
Need a "holding anything" conditional

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#437]
In a previous version we had a rainbow color to represent "holding any color." We should add this back as it will help with division.

**Comment by JWWeatherman** [comment]
We should probably also introduce a "holding nothing" conditional too. So we will have:

1. Holding a specified color.
2. Holding any color (rainbow).
3. Holding nothing (black).
4. Run always (white).

**Comment by giftedprimate** [comment]
@JWWeatherman here's a [CodePen](https://codepen.io/giftedprimate/pen/WYdOxM) of what the new conditionals will look like.

**Comment by giftedprimate** [comment]
@console-rastling Can you implement these in the compiler please.

**Comment by console-rastling** [comment]
Tested on "5. Conditionals Level 2" with this MBL:

(
 (defun pickupandmove (if 'empty (forward pickup)))
 (defun turnLeft (right right right))
 (defun loop (
              (if 'empty (pickupandmove (if 'any turnLeft)))) 
              (if 'any forward) 
              loop)
 loop
 )

Creates a "bump" free box pickup and turn with no need to drop the box.  Clearly useful for math levels.

![screenshot_2018-12-03_16-17-22](https://user-images.githubusercontent.com/35277479/49409801-05e4f680-f717-11e8-8a49-2f3ccc47bd49.png)

**Comment by giftedprimate** [comment]
Ui complete.

I used grey-scale-black instead of black so that the border would stand out against a black background.

Deployed to pre prod.

**Comment by giftedprimate** [comment]
Deployed to prod as well

**Comment by JWWeatherman** [comment]
Works great.
