### ISSUE TITLE
When you click on a function to edit it and you are already editing the function you get kicked back to main screen

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#439]
Repo:

1. Create a function called "golf ball".
2. Inside "golf ball" call "gold ball" (as you might in a tail recursive function).
3. Click on the function icon for golf ball you are calling inside golf ball.
4. Notice that you are kicked back to the main screen.

Expected:
Nothing should happen except maybe a message that says "you are already editing golf ball."

**Comment by giftedprimate** [comment]
This is solved as part of #450

**Comment by giftedprimate** [comment]
@JWWeatherman Fix deployed to pre-prod.

**Comment by giftedprimate** [comment]
@JWWeatherman Sorry wrong issue, fix for this will be part of refactor, #450

**Comment by JWWeatherman** [comment]
Confirmed in preprod.
