### ISSUE TITLE
Removing Functions from preliminary levels

### ISSUE THREAD

**Issue by codeShark149** [JWWeatherman/math_bot#44]
1.	In stage Walk 4, along with previous stages, I think removing the functions (Rocket, Uturn & Left turn) can be helpful. Keeping only the required operations can create the understanding of operations better. Then later, along each advanced stages, introducing the functional operations. This will make it more clear how functions are created using elementary operations. 
![issue3](https://user-images.githubusercontent.com/36541669/40654394-da96fefa-635b-11e8-9b90-e2efaf516779.PNG)

**Comment by JWWeatherman** [comment]
Closing for now. We want to get the user comfortable with the entire UI as soon as possible without causing confusion.
