### ISSUE TITLE
Create a "lightning" speed

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#440]
We currently have 1x, 2x and 3x speeds. Let's add a lightning speed that is our max speed and will execute the functions as quickly as we are capable.

We have had a couple user requests for this and right now 24 x 3 is taking a couple minutes to complete even at 3x.

Eventually our scrub forward/backward feature might eliminate the need for faster/slower speeds, but I'm assuming this will be much easier to implement.

**Comment by giftedprimate** [comment]
@JWWeatherman tentative solution is deployed to preprod.

**Comment by JWWeatherman** [comment]
This is an excellent feature in less than a 24 hour turn time. Nicely done!
