### ISSUE TITLE
Feature idea (not request yet because it might be hard)

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#441]
On some levels we have wanted to require that a single function would work to solve a variety of situations. For example an algo that would always move the robot to the bottom left corner no matter where he starts from. 

One idea is to have levels where the robots location moves, but you are unable to change the functions as they are locked. If you can't pass the level you need to return to a previous level and improve your algo.

Another idea is to have multiple robots on the screen. In order to pass the level you would need to write a single function that would cause all of the robots to complete the task even though they are starting in different locations. This would be particularly cool looking when teaching the coordinate system.

@giftedprimate @console-rastling any thoughts on the easiest way to do something like one of these?

Priority 2 is only for initial thoughts on the idea - not implementing something.

**Comment by giftedprimate** [comment]
@JWWeatherman @console-rastling The easiest solution would be option 2 (several robots) as far as the level flow goes. @console-rastling is this doable in the compiler?

**Comment by JWWeatherman** [comment]
Cool. Next time you guys do a call I’ll jump on so we can discuss for the first few mins.

**Comment by giftedprimate** [comment]
@JWWeatherman @console-rastling and I moved the days this week to tonight and tomorrow. I won't be able to hop on today however I will be on tomorrow, so if you are up for it how 'bout tomorrow?

**Comment by JWWeatherman** [comment]
Tomorrow is great. Send me the meeting invite for just tomorrow if you can.

**Comment by giftedprimate** [comment]
Here you go... 

https://hangouts.google.com/hangouts/_/calendar/cmljaGFyZEBtYXRoYm90LmNvbQ.7d34gs1e2mga4ibgao53h9lq41?authuser=0

This is a permanent link that we use every time.

**Comment by giftedprimate** [comment]
As per the meeting with JW tonight we will make a robot starting position that is 'unknown' to the user. 

### Level Gen
    - Will create a gird map key of (RR) that will be compiled into a flag that indicates the robot location is unknow.

### UI
    - Will display this feature is by having the robot move approx. every 1 sec. 

### Compiler
    - To ensure the user doesn't know the robots starting position the compiler will start the robot in a random location of its choosing.

**Comment by giftedprimate** [comment]
Closing in favor of #705
