### ISSUE TITLE
Nested function is not being called correctly

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#443]
Here is a video walkthrough of the bug:

https://drive.google.com/file/d/1R1IdpqNb1g97t3obqLOALyVLm2-HLr7W/view?usp=sharing

**Comment by giftedprimate** [comment]
@console-rastling I think this bug is related to the compiler not liking a single function inside another function.

**Comment by console-rastling** [comment]
The cause was old code that tried to heuristically block deadly recursive function loops where a function calls itself.  It is no longer needed, and it was preventing the MBL compiler from working as well, so the fix is the star-system branch.

**Comment by JWWeatherman** [comment]
Looks good.
