### ISSUE TITLE
Build a nested data structure to better facilitate extra level layers

### ISSUE THREAD

**Issue by giftedprimate** [JWWeatherman/math_bot#450]
Nested layers will be as follow...

- Super Cluster
   - Galaxy
     - Star System
       - Planet
         - Continent

This will require a complete rebuild of stats and lambdas and is going to require setting up new tables to handle them. After this refactor it should be much easier to add outer or inner layers. The nested data structure should be flattened, if possible, before storing in the database so that updates can remain in constant or linear time (avoid nested iterations).

Giftedprimate has already started this project on branch star-system.

**Comment by giftedprimate** [comment]
The star-system branch is MVP minus the ability to execute recursion console.rastling will update the compiler to handle the new data tomorrow night.

**Comment by giftedprimate** [comment]
@console-rastling Assigning this issue to you until the compiler is updated to handle a func field of None.

**Comment by giftedprimate** [comment]
@JWWeatherman Considering this issue MVP at this point. Any new issues can be filed desperately. Deployed to pre prod.

**Comment by JWWeatherman** [comment]
Looks solid.
