### ISSUE TITLE
Need to confirm when deleting a function or deleting all functions from main

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#451]
If a gamer accidentally deletes a ton of work it will be very discouraging. Anytime a single click could delete more than 10 mins of effort we should pop a confirm.

**Comment by j-chimienti** [comment]
What's a good way to describe effort? 

ATM I am starting clock when the app starts, and reseting when confirmed. 
So 10+ min window, user has to  confirm, even if level of effort is minimal

**Comment by JWWeatherman** [comment]
Sorry, my description wasn't clear. We should always ask for confirmation when deleting a function or when deleting all functions from main. I was just explaining that our policy should be always to confirm in situations where significant work could accidentally be lost.

**Comment by JWWeatherman** [comment]
Wow, this was a badly written bug, sorry about that. Here is a video that shows the two cases that need confirmation:

https://drive.google.com/file/d/1Ajo0f4rrwLZpHMXbNWSrnsdqm6YpONpG/view?usp=sharing

**Comment by j-chimienti** [comment]
I’m trying to think of a good solution for user to confirm function deactivation.


I don’t want to block game flow, but the solution I came up with involved creating endpoint to stage function, and then deactivating function separately

```
GET         /api/token/moveActiveToStaged/:tokenId/:activeIndex/:stagedIndex
GET         /api/token/deactivateFunction/:tokenId/:stagedIndex                    

```

So I'm thinking of good FE solution to confirm deactivation. The only way is to show a popup and lock the pieces, and wait for user confirmation.

**Comment by giftedprimate** [comment]
@j-chimienti It really is nice to have some help on the front end, I think between the two of us we will be able to take this to the next level!

I went ahead and merged #451. There is just a couple things to work on still.

1 - When I click trash can on the bar the puzzle pieces animate properly, but when I click the x to close it they continue to animate.

2 - When I deactivate a function and decide not to go through with it the function still remains in staged functions. It may be a good idea to prevent the function from being added to staged functions in the ui until the server responds which will then update the list.

Thanks!

**Comment by giftedprimate** [comment]
@j-chimienti I totally merged this before you moved the tile to Code complete, sorry about that. Everything looks fine to me at this point, are you happy with it?

**Comment by j-chimienti** [comment]
Yes I'm happy with functionality, and updated status to complete

**Comment by JWWeatherman** [comment]
@j-chimienti this is great. Good design solution and it has been working perfectly.
