### ISSUE TITLE
Keeping wrong codes in panel after failed run.

### ISSUE THREAD

**Issue by codeShark149** [JWWeatherman/math_bot#47]
The most major issue I have observed is, after the run of a sequence the panel list is getting cleared. This can be a bummer for longer sequences. As for every unsuccessful run, kids have to enter the entire sequence over again. My suggestion is don’t let the panel clear out after unsuccessful run.

**Comment by giftedprimate** [comment]
This is actually intentional in basic programming since the point is that we want the user to use each command deliberately in order for them to understand the concepts. In the following levels this will not be the case.

**Comment by giftedprimate** [comment]
I think it is important for the small children to not have an extra step (throw away what's in main) so that we can focus on teaching them how to commands work.

**Comment by JWWeatherman** [comment]
Sorry, didin't mean to close this. Too much multi-tasking today. This needs a little more user testing I think. We need to balance between frustrating the students with busy work and making sure they learn how to control the robot. Maybe we are already at that balance point, but let's leave this open until we take another look.

**Comment by codeShark149** [comment]
Yes, that makes sense.. May be we can think of killing it when code sequence exceeds some threshold.. more feedback will help..  well i don't know, how the feedback have came so far?? how many people tried the page??

**Comment by JWWeatherman** [comment]
Feedback is always hard to get, but the next big change is to add video tutorials. I think we will get people to progress further and provide more feedback with those.
