### ISSUE TITLE
Dragging the uturn on Programming level 7 doesn't work on Safari on Mac

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#497]
Repro:

Use Safari on a mac and attempt to complete level 7 of Programming. Notice you can't drag the u-turn function out to use it.

**Comment by JWWeatherman** [comment]
Not something that's worth messing with the holiday since most users are on Chrome.

**Comment by giftedprimate** [comment]
This is odd because there's nothing browser specific about that operation. Can you use all the other functions?

**Comment by giftedprimate** [comment]
I just tested it and verified you cannot drag any of the functions out of staged. I'll take care of it Friday.

**Comment by JWWeatherman** [comment]
Cool.

**Comment by giftedprimate** [comment]
@JWWeatherman Fix deployed to pre-prod.

**Comment by JWWeatherman** [comment]
Fixed.

**Comment by giftedprimate** [comment]
Deployed to prod.
