### ISSUE TITLE
Cross browser optimization 

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#5]
- Optimization is complete for all phone sizes (may need some touch up)
- Need to optimize for tablet sized devices

**Comment by giftedprimate** [comment]
As of this date app is optimized for Chrome, Safari, Firefox, and iOS (all iOS browsers are the same under the hood). These changes are deployed to pre-prod and awaiting approval from JW.

Next up is IE which should be finished this week.

**Comment by JWWeatherman** [comment]
Verified on chrome and mac. Green light to deploy even though I will keep this open until we have done more testing on Safari, Firefox, IOS and IE.

**Comment by giftedprimate** [comment]
I am going to close this issue in favor of being specific to a component.
