### ISSUE TITLE
Can't click on the profile picture in Safari (preprod only)

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#514]
Looks like this is related to a recent code change as it won't repro on production, but using Safari on Mac I am unable to click my profile picture to change levels or sign-out.

**Comment by JWWeatherman** [comment]
I also can't click on the stars for hints and this is also working fine in production (but broken in pre-prod).

**Comment by giftedprimate** [comment]
Deployed to pre-prod

**Comment by JWWeatherman** [comment]
Verified.
