### ISSUE TITLE
Update portal and robot locations for coordinate levels 

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#527]
For the coordinates planet the portal is in the wrong location on a few of the levels and its actually better if the robot is randomly placed. Assuming the bottom left corner is location (1,1) and the first number increments as you move right and the second number increments as you move up.

Level 2: portal at (1,1) bottom left corner - make the robot start at (3,3)
Level 3: portal at (3,3) robot normal position - make robot start at (8,5)
Level 4: portal at (6,1) (remove kitty) robot start at (1,4)
Level 5: portal at (6,2) robot start at (9,2)
Level 6: portal at (2,2) robot start at (5,5)
Level 7: portal at (2,3) robot start at (3,10)

**Comment by JWWeatherman** [comment]
On level 3 the portal is in the correct position, but the robot it is at (1,1) instead of (8,5)
On level 5 the portal is it (7,1) instead of (6,2) and the robot is at (10,3) instead of (9,2)
On level 7 the portal is at (3,3) instead of (2,3). Also the robot should be at (7,5) but this was my mistake because I told you to put it in an invalid position.

**Comment by giftedprimate** [comment]
Getting this right is a pain for me because I think starting from the top left and with 0 being the first index. I'll try again.

**Comment by JWWeatherman** [comment]
Totally. I was tempted to change the board so the robot walks on the lines, but I think that would be confusing too.

**Comment by giftedprimate** [comment]
Did you edit the issue comment? Because I know for a fact it didn't say that yesterday, I thought the positioning was odd.

**Comment by giftedprimate** [comment]
It's deployed again.

**Comment by JWWeatherman** [comment]
Works great.
