### ISSUE TITLE
On coordinates planets remove the rocket and give turn left and u-turn functions

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#530]
Right now we give them the rocket function, but that should be removed and we should add the turn left and uturn functions. And we should have those functions populated correctly.

This is not blocking me, but we should fix before deployment to production.

**Comment by giftedprimate** [comment]
@JWWeatherman  You should have all your functions on that level on this level in staged functions unless you have used them.

**Comment by JWWeatherman** [comment]
Oh, ok. Makes sense. Disregard.

**Comment by giftedprimate** [comment]
I didn't set any restrictions and all previously generated functions are added to a level if didn't use it on the level it was generated on.

**Comment by giftedprimate** [comment]
Just tested and it should be working
