### ISSUE TITLE
When deactivating a function it the icon should replace the name.

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#531]
Repo:

1. Drag a function into the staging area.
2. Open the function, name it, and click on the icon to change it to display the name.
3. Drag the function back into the unused icons area and confirm you want to deactivate it.
4. Notice that it still shows the name you gave it.

Expected:
The unused function should revert to displaying the icon.

**Comment by JWWeatherman** [comment]
The name of the function is also retained. It should be removed so the icon is reset to the unused status.

**Comment by giftedprimate** [comment]
@JWWeatherman this is part of #451 which is in the inspection column. It may be better to add this to that conversation.

**Comment by giftedprimate** [comment]
@JWWeatherman Or nevermind, it is different. I can fix this in 5 minutes.

**Comment by giftedprimate** [comment]
Deployed to pre prod.

**Comment by JWWeatherman** [comment]
Working great.
