### ISSUE TITLE
Needs to unlock Single Digit Arithmetic if last level in Conditional beat

### ISSUE THREAD

**Issue by giftedprimate** [JWWeatherman/math_bot#536]
This is issue is being filed retroactively, was solved by #532.

**Comment by giftedprimate** [comment]
@JWWeatherman Fix deployed to pre prod. This one may be impossible to test in pre prod unless you have a legacy account with all the levels Programming levels beat. It is working.

**Comment by JWWeatherman** [comment]
Cool.
