### ISSUE TITLE
Highlighting of levels is gradated 

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#546]
On the right is production and the highlight is correct. On the left is pre-prod and the highlight in a gradient. @giftedprimate is this a good bug for Will since it isn't a high priority?

<img width="882" alt="screen shot 2018-11-27 at 9 39 16 am" src="https://user-images.githubusercontent.com/32912678/49088913-5ac0d280-f228-11e8-9103-c58da6028d00.png">

**Comment by giftedprimate** [comment]
It isn't a bug, I did that on purpose because when I implemented this feature originally you said it still wasn't very obvious which level was selected. I can switch it back in less than 1 min. Will is working on a more important problem #476 so I'll just switch it.

**Comment by JWWeatherman** [comment]
Ok, cool. I think it looks great as is. Not sure what I was thinking.

**Comment by giftedprimate** [comment]
I kinda like the old way better. If you change your mind I can change it back really easily.

**Comment by JWWeatherman** [comment]
Sorry, that comment was unclear. I prefer the non-gradient on level highlighting. The version that is currently on production (right side of the above screenshot). I also just notice the gradient/drop shadow on the profile image in the upper right hand corner. I don't really like that either.

**Comment by giftedprimate** [comment]
The radial gradient on the profile image has been removed already in pre-prod, that was a bug related to a CSS selector... 

![image](https://user-images.githubusercontent.com/33336425/49090211-43371900-f22b-11e8-93bd-990dad4f4e84.png)

**Comment by giftedprimate** [comment]
I'll change the levels outline today as well along with #547

**Comment by JWWeatherman** [comment]
Awesome.

**Comment by giftedprimate** [comment]
Deployed to pre prod

**Comment by JWWeatherman** [comment]
Looks great now.
