### ISSUE TITLE
Ctrl-Space doesn't open sandbox in preprod

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#547]
Still works in prod, but can't get into sandbox in pre-prod.

**Comment by giftedprimate** [comment]
It doesn't exist right now in pre-prod. I can re-implement it today.

**Comment by JWWeatherman** [comment]
Ok, is my old code from the sandbox in pre-prod lost or still there? No biggie either way.

**Comment by giftedprimate** [comment]
It is lost because the refactor completely changed how that works.

I'd like to implement a sandbox as a star-system so that our users can play around with it. Would that be ok with you? This will not be a big deal at all to implement.

**Comment by JWWeatherman** [comment]
Yeah, actually that will be fine as long as we automatically play a hint video that explains what it is. That will address my concern that people will get lost in there not knowing the purpose.

**Comment by JWWeatherman** [comment]
Is it possible to recover that code from git? It will probably take me 5 hours to recreate it so if it takes much longer than that it's not worth the effort.

**Comment by giftedprimate** [comment]
Recovering the code from git will not solve this problem. 

It's easy to implement it either way, would you like it to be ctl+space or a star-system? I can implement this in less than 2 hrs.

**Comment by giftedprimate** [comment]
You should have all your functions regardless if you are logged in with the same account you logged in with before. The functions are not tied to any of the levels. Do you not have your functions?

**Comment by giftedprimate** [comment]
The func field is not being transferred over. You must have the functions but they are empty when you open them, is this the case?

**Comment by giftedprimate** [comment]
Deployed to pre prod. It is represented as a starSystem instead of ctl+space

**Comment by JWWeatherman** [comment]
Much easier. Good solution.
