### ISSUE TITLE
Change Planet 4 Level 1 to 2 * 2

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#554]
Once I started recording I realized that multiplying by 1 is a terrible way to start. I'm not blocked for recording videos as I can use a future level and pretend it is the first level.

**Comment by giftedprimate** [comment]
Level 4 is 8 * 1
Level 13 is 1 * 1

Are these ok?

**Comment by JWWeatherman** [comment]
Yeah, it’s cool. Just don’t want to start with a *1

**Comment by JWWeatherman** [comment]
I just realized that level 2 is 2*5 = 10, but I was supposed to keep these limited to single digit answers. Can you change that to 2*4 too.

**Comment by JWWeatherman** [comment]
Actually lemme run through these all so I don't keep asking for random changes.

**Comment by giftedprimate** [comment]
k

**Comment by JWWeatherman** [comment]
Level 1 = 2*2 (change needed)
Level 2 = 3*2 (change needed)
Level 3 = 4*2 
Level 4 = 8*1
Level 5 = 4*2
Level 6 = 3*2
Level 7 = 2*4
Level 8 = 4*2
Level 9 = 2*3
Level 10 = 2*2
Level 11 = 3*2
Level 12 = 4*2
Level 13 = 1*1
Level 14 = 2*3
Level 15 = 4*2
Level 16 = 3*3
Level 17 = 2*4
Level 18 = 1*9

Looks like they are all fine except the first two.

**Comment by giftedprimate** [comment]
Deployed

**Comment by JWWeatherman** [comment]
thx dude!
