### ISSUE TITLE
Add more levels to the coordinates planet

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#555]
Let's make 18 levels on the coordinates planet. Repeat the existing problems randomly and add this one too:

I am not blocked for recording, because I can just swing back and record the new level later.

Robot at position (4,4)
Portal at position (3,2)

**Comment by giftedprimate** [comment]
Deployed to pre prod.

**Comment by JWWeatherman** [comment]
Looks great.
