### ISSUE TITLE
When you fail to complete the level pulse the hint stars and the reset button

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#556]
This will make it less likely someone gets stuck not knowing what to do next.

**Comment by giftedprimate** [comment]
I am working on this now.

You can also just start programming again to reset the level. This may be worth mentioning in one of the free hints.

**Comment by giftedprimate** [comment]
Deployed to pre prod.

**Comment by JWWeatherman** [comment]
This looks good. Is it easy to slow down the pulses? They are kind of intense. Maybe make each pulse take about a second?

**Comment by giftedprimate** [comment]
Not a big deal at all, I'll take care of this first thing today.

**Comment by giftedprimate** [comment]
Deployed to pre prod. 

I ended up going with a slow flash instead of a pulse because it is more subtle and doesn't feel as aggressive. Slowing down the pulse or tada animations looked weird. I also hide the green bar while the animation runs so that the refresh button stands out better.

**Comment by JWWeatherman** [comment]
Looks great.
