### ISSUE TITLE
When deactivating a function another function is deactivated instead

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#559]
I don't have a great set of repo steps on this as it doesn't happen everytime, but here is a screen recording that shows the bug:

https://drive.google.com/file/d/1P0_jAuroSNiq-sLho8Ryi3B1Ws4_sFHg/view?usp=sharing

I don't know if it reproduces in production or only preprod and this is not blocking me on videos.

**Comment by giftedprimate** [comment]
Try to actually deactivate swap 1 for 1 and see if that is actually the one that gets deactivated. This may just be a bug on the front end only.

**Comment by giftedprimate** [comment]
I can confirm it is trying to deactivate the wrong function

**Comment by JWWeatherman** [comment]
Cool.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by JWWeatherman** [comment]
Cool. That does sound tricky. I’ve also noticed that it’s really easy to accidentally re order your functions when using them. Not sure if the solution will (or can) address this, but thought it worth mentioning.

**Comment by giftedprimate** [comment]
I have wrestled with this problem in the past and gave up in favor of other tasks. I'll work on it again, it is annoying the way they move so easily. I think this is why we didn't allow for re-arranging functions in the beginning.

**Comment by JWWeatherman** [comment]
Cool. It might be as good as it can be, but it might be worth a quick battle if its closely enough related to this bug.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by JWWeatherman** [comment]
I actually like the way they sort easily. Could we only save the new position when it is dropped? That way if you accidentally drag over something as you are dragging it out it dosen't effect the sort order?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by giftedprimate** [comment]
That already happens. The problem is that when you drag out of the draggable and the ghost moves it changes the sortable index.

**Comment by giftedprimate** [comment]
It's not as good as it gets, it never is. ;)

**Comment by giftedprimate** [comment]
Ya it's sortable js moving a function even though it was dropped into a different droppable. I have an idea of how to fix it. It shouldn't be to bad.

**Comment by giftedprimate** [comment]
If you run into this bug in the mean time all you need to do to correct the indexing is refresh.

**Comment by JWWeatherman** [comment]
Excellent.

**Comment by giftedprimate** [comment]
What do you think of a little switch that turns sort on and off?

**Comment by giftedprimate** [comment]
One sec and I'll send a demo.

**Comment by giftedprimate** [comment]
Nm, the solution turned out to be easy. If staged functions is open I simply disable sorting.

**Comment by giftedprimate** [comment]
Almost finished with this.

**Comment by giftedprimate** [comment]
Deployed to pre prod.

The problem is that SortableJs is not indexing the functions properly so the order in the ui does not always match our data structure. The fix was to use a data attribute of the functions created id so that we are not dependent on the index because we can do a find on the active array with the created id. 

This implementation will still show the active functions in the wrong order if Sortable attempts to sort when dropping the function elsewhere but this does not matter to the server since the server filters out the moved functions therefore order does not matter.

I will file another bug for ensuring active functions ui order always matches the active functions array, I will work on this next.

**Comment by JWWeatherman** [comment]
Looks good. Can't see anymore repro.
