### ISSUE TITLE
Need more unused functions

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#571]
Right now my JW account on pre-prod is using about 50 functions. I only have a couple left unused. Can we add another 50 so we have a total of 100 unused functions?

**Comment by giftedprimate** [comment]
It may be best to refactor this so that we have unlimited 'staged' functions by using the noun project API instead of hard coding the link like we are doing now. I would still only render 50, but there would always be 50 available. 

Does this sound good to you?

**Comment by JWWeatherman** [comment]
I’m not sure it’s worth the effort. I think more than 100 and our UX is getting very shaky.

**Comment by JWWeatherman** [comment]
I suppose if the feature is less than 3x more work than manually adding 50 it’s probably worth doing.

**Comment by giftedprimate** [comment]
It will get shaky if we hard code 100 image urls. If you use the api we will only call for what we need at any given time, plus we don't have to store them that way.

**Comment by giftedprimate** [comment]
Hard coding will be trivial compared to using the api, but we are going to be kicking another problem down the road. I'll leave it up to you to decide.

**Comment by giftedprimate** [comment]
*the noun project would be storing all the images.

**Comment by JWWeatherman** [comment]
Ok, let hardcode.

**Comment by giftedprimate** [comment]
k

**Comment by giftedprimate** [comment]
Hey Will,

I need you to get 50 images from the noun project and add them to the bottom of the `funcImages` property in `ui/src/assets/assets.js` starting at `'51'`. 

Just pick images that are similar to what we already have and store them in your cloudinary account. 

Thanks!

**Comment by willweatherman** [comment]
Hi, 

This is rated a priority 3 is that higher than 2?

Thanks-
Will.

**Comment by willweatherman** [comment]
Ok.

**Comment by JWWeatherman** [comment]
No, higher priority is a lower number.

**Comment by giftedprimate** [comment]
Huh?

**Comment by giftedprimate** [comment]
I am assigning this to myself as well because I am going to start working on the backend of this feature now.

**Comment by giftedprimate** [comment]
Back end is MVP. @willweatherman holler at me when you to your PR with the new images.

**Comment by giftedprimate** [comment]
@willweatherman do a pull request when the planets are ready. Thanks.

**Comment by willweatherman** [comment]
Hi, I will. It should be done in the next 3 hours.

**Comment by giftedprimate** [comment]
@willweatherman Replace all the playing card icons with something else. I understand why you picked playing cards, however the icon features are so tiny that many of them look exactly the same. Also I noticed a duplicate, it is very important this does not happen.

Please do that ASAP. Thanks!

![image](https://user-images.githubusercontent.com/33336425/49389476-67479e00-f6f4-11e8-907d-c2b2d7776689.png)

**Comment by willweatherman** [comment]
Ok I'll start on it now.

**Comment by giftedprimate** [comment]
Awesome, thanks!

**Comment by willweatherman** [comment]
@giftedprimate I just finished adding the new images and creating a pull request.

**Comment by giftedprimate** [comment]
Cool, thanks!

**Comment by giftedprimate** [comment]
Deployed to pre prod

**Comment by JWWeatherman** [comment]
I'm still not seeing any available functions in my account.
<img width="1099" alt="screen shot 2018-12-03 at 5 15 49 pm" src="https://user-images.githubusercontent.com/32912678/49404977-1dc07880-f71f-11e8-92ce-089eb524ccfa.png">

**Comment by giftedprimate** [comment]
Deactivate a function or 2

**Comment by giftedprimate** [comment]
It adds and removes them as you activate/deactivate functions ensuring there is always 50 or 51

**Comment by JWWeatherman** [comment]
I just attempted to deactivate two functions. The first one was the triangle. It left it in my function area below so I dragged it in two more times. Now it is still below and shows 3 times in the available functions. Repeated using the magnifying glass and got same results.

<img width="1099" alt="screen shot 2018-12-03 at 5 19 23 pm" src="https://user-images.githubusercontent.com/32912678/49405207-bc4cd980-f71f-11e8-8b3a-5bc8b81fab5f.png">

**Comment by giftedprimate** [comment]
should work now, and I made it so you will have 50 on initial load as well as adding/removing functions as you activate/deactivate them. Deployed to pre prod

**Comment by giftedprimate** [comment]
Deployed to prod as well

**Comment by JWWeatherman** [comment]
Great solution. Good job guys.
