### ISSUE TITLE
New Hint Videos

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#579]
Coordinates:
1 hint 1 https://youtu.be/7HsTgJq7Ir0
1 Hint 2 https://youtu.be/qBB6_IS3THU
1 Hint 3 https://youtu.be/sgfjPCRt33g
2 https://youtu.be/aFkFxgIhIhI
3 https://www.youtube.com/watch?v=-b8Ii57XREA
4 https://www.youtube.com/watch?v=FOp1-UPtQEc
5 https://youtu.be/nAYeSfUjLj8
6 https://youtu.be/wcVNnhnqaCc
7 https://www.youtube.com/watch?v=FOp1-UPtQEc&t=3s
8 https://youtu.be/G_zAgyv8C48
9 https://www.youtube.com/watch?v=FOp1-UPtQEc&t=3s
10 https://www.youtube.com/watch?v=nAYeSfUjLj8tw
11 https://www.youtube.com/watch?v=wcVNnhnqaCc
12 https://www.youtube.com/watch?v=-b8Ii57XREA&t=2s
13 https://www.youtube.com/watch?v=aFkFxgIhIhI
14 https://www.youtube.com/watch?v=uwR5lrMaUSE
15 https://www.youtube.com/watch?v=wcVNnhnqaCc
16 https://www.youtube.com/watch?v=nAYeSfUjLj8
17 https://www.youtube.com/watch?v=G_zAgyv8C48
18 https://youtu.be/nYlx6ogp9RA

Addition:
1 https://www.youtube.com/watch?v=HiFTav92mgA
2 https://www.youtube.com/watch?v=_LB_A7YVKEM
3 https://www.youtube.com/watch?v=44ABmHetZSA
4 https://www.youtube.com/watch?v=J9RYEDKdeqs
5 https://www.youtube.com/watch?v=7W6lotbo6kQ
6 https://www.youtube.com/watch?v=jaqoLaIO0NI
7 https://www.youtube.com/watch?v=JjmTJDV_31o
8 https://www.youtube.com/watch?v=Gc7xo_ulKDE
9 https://www.youtube.com/watch?v=2E7v5pqtSD8
10 https://www.youtube.com/watch?v=6sslR8niZ6k
11 https://www.youtube.com/watch?v=GGOHvwiMR6I
12 https://www.youtube.com/watch?v=GHTrhjsDybI
13 https://www.youtube.com/watch?v=vMivufjmdpM
14 https://www.youtube.com/watch?v=LxDXU2wI_xE
15 https://www.youtube.com/watch?v=1TXsUFUaXz8
16 https://www.youtube.com/watch?v=Wr_7mWckjEc
17 https://www.youtube.com/watch?v=8N-gzmF-vW0
18 https://www.youtube.com/watch?v=F9m_Yd9yqb0

Subtraction:
1 https://www.youtube.com/watch?v=Um2NctlzVN0
2 https://www.youtube.com/watch?v=O-Ha5dLqPlY
3 https://www.youtube.com/watch?v=cS9jmUcvO0U
4 https://www.youtube.com/watch?v=KLa7DiXFXGE
5 https://www.youtube.com/watch?v=owjkOZjrpEw
6 https://www.youtube.com/watch?v=p2XMi7paiv4
7 https://www.youtube.com/watch?v=O1a0ovj96a8
8 https://www.youtube.com/watch?v=qPCxUeOuXn4
9 https://www.youtube.com/watch?v=SnWWZiZhEGk
10 https://www.youtube.com/watch?v=39JonuJeLWc
11 https://www.youtube.com/watch?v=cUIy67SSrSM
12 https://www.youtube.com/watch?v=cS9jmUcvO0U
13 https://www.youtube.com/watch?v=CA7hdeUv34g
14 https://www.youtube.com/watch?v=lsK7HLN4eUI
15 https://www.youtube.com/watch?v=Y3J26uTCHbc
16 https://www.youtube.com/watch?v=rnVUXdUUJ5g
17 https://www.youtube.com/watch?v=owjkOZjrpEw
18 https://www.youtube.com/watch?v=Y3J26uTCHbc

Multiplication
1 https://www.youtube.com/watch?v=ppkafvWniJE
2 https://www.youtube.com/watch?v=Tvb8xXFWsUQ
3 https://www.youtube.com/watch?v=7G-P2mHhpUA
4 https://www.youtube.com/watch?v=z4oUZIRGMFA
5 https://www.youtube.com/watch?v=7G-P2mHhpUA
6 https://www.youtube.com/watch?v=Tvb8xXFWsUQ
7 Hint 1 https://www.youtube.com/watch?v=PXvp81TuhQY
7 Hint 2 https://www.youtube.com/watch?v=2tuaC-SdCJw
8 https://www.youtube.com/watch?v=7G-P2mHhpUA
9 Hint 1 https://www.youtube.com/watch?v=8yOP_lpxA2A
9 Hint 2 https://www.youtube.com/watch?v=Yk3ABZWYKYQ
10 https://www.youtube.com/watch?v=ppkafvWniJE
11 https://www.youtube.com/watch?v=Tvb8xXFWsUQ
12 https://www.youtube.com/watch?v=7G-P2mHhpUA
13 https://www.youtube.com/watch?v=Sr8QUWOdh24
14 Hint 1 https://www.youtube.com/watch?v=8yOP_lpxA2A
14 Hint 2 https://www.youtube.com/watch?v=Yk3ABZWYKYQ
15 https://www.youtube.com/watch?v=7G-P2mHhpUA
16 https://www.youtube.com/watch?v=aoMlhKGn5yI
17 Hint 1 https://www.youtube.com/watch?v=PXvp81TuhQY
17 Hint 2 https://www.youtube.com/watch?v=2tuaC-SdCJw
18 Hint 1 https://youtu.be/bI-JMwQrq0k
18 Hint 2 https://youtu.be/eiYAQ8o-ZfE

Division:
1 https://www.youtube.com/watch?v=fD9NKD_pL_I&t=1s
2 https://www.youtube.com/watch?v=P9ijq_7a7_M
3 https://www.youtube.com/watch?v=0UxfRBDWbts
4 https://www.youtube.com/watch?v=olV6It6P9D4
5 https://www.youtube.com/watch?v=dJPwXUYtaAI
6 https://www.youtube.com/watch?v=2c7DIBVQN74
7 https://www.youtube.com/watch?v=MjHJ6DV1l9g
8 https://www.youtube.com/watch?v=_G73JWQfwPc
9 https://www.youtube.com/watch?v=rmV7KFe1iPs
10 https://www.youtube.com/watch?v=F_88AGIEO0U
11 https://www.youtube.com/watch?v=fD9NKD_pL_I&t=1s
12 https://www.youtube.com/watch?v=MjHJ6DV1l9g
13 https://www.youtube.com/watch?v=2c7DIBVQN74
14 https://www.youtube.com/watch?v=P9ijq_7a7_M
15 https://www.youtube.com/watch?v=YrdnD4igIhs
16 https://www.youtube.com/watch?v=dJPwXUYtaAI
17 https://www.youtube.com/watch?v=olV6It6P9D4
18 https://www.youtube.com/watch?v=fD9NKD_pL_I&t=1s

Exponents
1 https://www.youtube.com/watch?v=ydFF5zInf0g
2 https://www.youtube.com/watch?v=WBYvnlDIf4w
3 https://www.youtube.com/watch?v=zmKzvOe2_VY
4 https://www.youtube.com/watch?v=fhRgMSskpq8
5 https://www.youtube.com/watch?v=ydFF5zInf0g
6 https://www.youtube.com/watch?v=WBYvnlDIf4w
7 https://youtu.be/4jKByB8iQdk
8 https://www.youtube.com/watch?v=fhRgMSskpq8
9 https://youtu.be/4jKByB8iQdk
10 https://www.youtube.com/watch?v=WBYvnlDIf4w
11 https://www.youtube.com/watch?v=WBYvnlDIf4w
12 https://www.youtube.com/watch?v=ydFF5zInf0g
13 https://www.youtube.com/watch?v=zmKzvOe2_VY
14 https://www.youtube.com/watch?v=ydFF5zInf0g
15 10 https://www.youtube.com/watch?v=WBYvnlDIf4w
16 https://www.youtube.com/watch?v=ydFF5zInf0g
17 https://youtu.be/4jKByB8iQdk
18 https://www.youtube.com/watch?v=WBYvnlDIf4w

Roots
1. https://www.youtube.com/watch?v=e74jGknaZXM
2. https://www.youtube.com/watch?v=rdG49Ple81Y
3. https://www.youtube.com/watch?v=tmXdXQ_vqV8
4. https://www.youtube.com/watch?v=e74jGknaZXM
5. https://www.youtube.com/watch?v=rdG49Ple81Y
6. https://www.youtube.com/watch?v=tmXdXQ_vqV8
7. https://www.youtube.com/watch?v=e74jGknaZXM
8. https://www.youtube.com/watch?v=bmtjgPkY0nU
9. https://www.youtube.com/watch?v=rdG49Ple81Y
10. https://www.youtube.com/watch?v=e74jGknaZXM
11. https://www.youtube.com/watch?v=e74jGknaZXM
12. https://www.youtube.com/watch?v=tmXdXQ_vqV8&t=15s
13 https://www.youtube.com/watch?v=bmtjgPkY0nU&t=21s
14 https://www.youtube.com/watch?v=tmXdXQ_vqV8&t=15s
15 https://www.youtube.com/watch?v=e74jGknaZXM&t=10s
16 https://www.youtube.com/watch?v=tmXdXQ_vqV8&t=15s
17 https://www.youtube.com/watch?v=rdG49Ple81Y&t=28s
18 https://www.youtube.com/watch?v=e74jGknaZXM&t=10s

**Comment by giftedprimate** [comment]
No problem, I'll get these done today.

**Comment by giftedprimate** [comment]
@JWWeatherman Coordinates 4 and 7 are duplicates and the portal is in different spots.

**Comment by giftedprimate** [comment]
@jwweatherman nm, I found the correct video for level 7.

**Comment by giftedprimate** [comment]
Deployed to pre prod.

**Comment by JWWeatherman** [comment]
Random checks looked good.
