### ISSUE TITLE
Free Hints - Single Digit Arithmetic

### ISSUE THREAD

**Issue by giftedprimate** [JWWeatherman/math_bot#583]
@JWWeatherman are you going to record free hints for these planets? Or should I use the first hint for each of them?

**Comment by JWWeatherman** [comment]
Coordinates - Play the third hint video for free on the first level.
Addition - Play the only hint video for the first level.
Subtraction - Play the only hint video for the first level.
Multiplication - Play the only hint video for the first level.
Division - Play the only hint video for the first level.
Exponents - Play the only hint video for the first level.
Roots - Play the only hint video for the first level.

**Comment by giftedprimate** [comment]
Deployed to pre prod

**Comment by giftedprimate** [comment]
Deploy to prod as well
