### ISSUE TITLE
Setup Prettier for UI Directory

### ISSUE THREAD

**Issue by giftedprimate** [JWWeatherman/math_bot#587]
@j-chimienti has some experience with Prettier and is willing to set it up.

**Comment by j-chimienti** [comment]
**Installation**

1. install File Watchers Plugin

1. Set up ESLINT

**note** I chose so set up w/ ESLint as prettier does not have space before function parenthases

<img width="1125" alt="screen shot 2018-12-04 at 11 05 36 am" src="https://user-images.githubusercontent.com/16620120/49455130-a0474780-f7b4-11e8-820e-9b714cb33da6.png">

note: change show console setting to error / none

**Comment by giftedprimate** [comment]
Good call, I like the space before the parens. Thanks for setting that up!

**Comment by j-chimienti** [comment]
**Limit Scope to FE**

click include recursively ui folder

<img width="819" alt="screen shot 2018-12-04 at 11 23 29 am" src="https://user-images.githubusercontent.com/16620120/49456477-2bc1d800-f7b7-11e8-9c43-9f0cced00fa6.png">

**Comment by j-chimienti** [comment]
I like the space as well, prettier apparently doesnt

**Comment by j-chimienti** [comment]
I can also add a git hook @giftedprimate so committed files are formatted

**Comment by giftedprimate** [comment]
@j-chimienti Go for it, thanks!

**Comment by j-chimienti** [comment]
Git hooks > Intellij

No need to install, and runs on every commit and push. And w/ above settings, I was having 10+ processes running all the time, and @giftedprimate noticed code being removed in real time


**Todo**:

>  We can setup ScalaFmt to work with sbt so that we don't need to plugin to run it, it formats on compile

**Comment by giftedprimate** [comment]
Closing this issue and will open a new for setting up `ScalaFmt` in `sbt`
