### ISSUE TITLE
MBL: Change function syntax

### ISSUE THREAD

**Issue by console-rastling** [JWWeatherman/math_bot#589]
Change function syntax from:

(defun name (commands))

To:

(name => commands)

Chang color conditional syntax from;

(if 'color (commands))

To:

(name => if 'color (commands))

**Comment by console-rastling** [comment]
Tested on "5. Conditionals Level 2" with this MBL (otherwise known as "00041"):

Couldn't easily remove the the paren from the "conditional function" variant but it's pretty close to the desired syntax anyway.  

```
(
 (pickupandmove => (if 'empty (forward pickup)))
 (turnLeft => (right right right))
 (loop => (
              (if 'empty pickupandmove (if 'any turnLeft))) 
              (if 'any forward) 
              loop)
 loop
 )
```

![screenshot_2018-12-04_16-51-30](https://user-images.githubusercontent.com/35277479/49482654-e1575000-f7e4-11e8-88be-3d41581cafb8.png)

**Comment by giftedprimate** [comment]
@JWWeatherman This is deployed to pre-prod. 

'Advanced' mode is not complete yet however this piece of it is mvp

**Comment by willweatherman** [comment]
@giftedprimate I am able to test if I am at the beginning of the stream so it will highlight stuff at the beginning of the line.

**Comment by giftedprimate** [comment]
@willweatherman this isn't the correct issue, please move the comment to #476

**Comment by JWWeatherman** [comment]
Very cool!
