### ISSUE TITLE
Free Hints For Sandbox levels

### ISSUE THREAD

**Issue by giftedprimate** [JWWeatherman/math_bot#596]
It might be a good idea to make a free hint that plays for all the sandbox levels explaining that they are not part of the game.

**Comment by JWWeatherman** [comment]
Good idea. Here you go:
https://youtu.be/sZhPULEkN2k

**Comment by giftedprimate** [comment]
Deployed to pre-prod and prod.

**Comment by JWWeatherman** [comment]
Looks great.
