### ISSUE TITLE
Implement Interactive Tutorial

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#6]
- User should not need to be able to read in order to understand tutorial
- Should use a hand similar to LightBot (http://lightbot.com/)
- Tutorial should have no effect on the actual state (should make ghost copies of dom elements, not using the Vue model).
- Tutorial config should be added to the level config in conf/assets, if Scala help is needed let us know.

**Comment by giftedprimate** [comment]
Close because this will be handled by the videos.
