### ISSUE TITLE
Main is not executing functions in order

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#620]
Main is not executing functions in the order displayed.

https://drive.google.com/file/d/1C_gj-WUcv71G6ZTqWQ3a36WBzFmWjyqv/view?usp=sharing

**Comment by JWWeatherman** [comment]
I saw this issue in pre-prod. I don't know if it is in issue in production.

**Comment by giftedprimate** [comment]
This is messed up, I used a sortBy on mains function last night, dumb mistake. I'm hot fixing prod now.

**Comment by giftedprimate** [comment]
Deployed to pre-prod and prd.

**Comment by JWWeatherman** [comment]
Good fix.
