### ISSUE TITLE
Need new denomination blocks in sandbox

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#627]
#416 shows various denominations for blocks. I specifically need negative numbers (-1, -10, -100) to develop the next set of levels, but maybe we should just go ahead and enable all of these blocks in the sandbox.

**Comment by giftedprimate** [comment]
@console-rastling and I are going to need to change the compiler to be value based instead of color based since this is going to be a pain to manage using that many colors to identify the values. We can do this right after we get the compiler ready for the scrub-through feature.

**Comment by giftedprimate** [comment]
@console-rastling after we get finished with #438 we should refactor the server to use the value of the tool instead of the color and leave the color association to the client.

**Comment by giftedprimate** [comment]
### Denominations needed

- (-.00001)
- (-.0001)
- (-.001)
- (-.01) 
- (-.1)
- (-1)
- (-10)
- (-100)
- (-1000)
- (-10000)
- x
- y
- z
- .00001
- .0001
- .001
- .01
- .1
- 1
- 10
- 100
- 1000
- 10000

**Comment by giftedprimate** [comment]
@console-rastling Added all the denominations to the compiler. I will probably be able to tackle this early next week on the front end.

**Comment by giftedprimate** [comment]
Starting this feature now.

**Comment by giftedprimate** [comment]
This is deployed to pre-prod. You can see all the denominations in sandbox.

I also simplified the sandbox to be just a single continent that is not part of the overall game making it so you can open the sandbox, play around, then navigate back to the profile and be where you left off in the game.

**Comment by JWWeatherman** [comment]
Loving it.
