### ISSUE TITLE
Lets remove the social sharing buttons on the video player

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#634]
I think the best spot for these is still on the completion screen, but here it's too cluttered.

<img width="840" alt="screen shot 2018-12-12 at 12 43 35 am" src="https://user-images.githubusercontent.com/32912678/49849346-19433200-fda7-11e8-89c0-858515efe98d.png">

**Comment by giftedprimate** [comment]
@willweatherman can you take care of this for me? Just remove the social sharing component from `Video_hints.vue`. Make sure to remove the import and declaration as well. Thanks.

**Comment by willweatherman** [comment]
Yep.

**Comment by giftedprimate** [comment]
@JWWeatherman deployed to pre-prod

**Comment by JWWeatherman** [comment]
Looks good.
