### ISSUE TITLE
Need to replace 'grey' func images to 'white' ones

### ISSUE THREAD

**Issue by giftedprimate** [JWWeatherman/math_bot#636]
In `ui/src/assets/assets.js` we need to find the images that are `grey` and replace them with the same image in `white`.

**Comment by giftedprimate** [comment]
Example, notice the image on the left is grey and the image on the right is white. Essentially all the images imported from the original designer were `#cccccc`  and the images recently imported are `#ffffff`. @JWWeatherman likes the white images best. 

The important this is to make sure the images are the exact same image found at the index in `assets.js` otherwise the users images will be out of wack from what they built.

![image](https://user-images.githubusercontent.com/33336425/49889677-21838780-fe10-11e8-9b34-850d3dbdb630.png)

**Comment by willweatherman** [comment]
Ok.

**Comment by willweatherman** [comment]
Hi, Ok can you tell me if there from the noun project and if they all have the same author. If not I'll keep looking.

Thanks-
Will.

**Comment by giftedprimate** [comment]
They need to be the exact same otherwise it will screw things up. They should be from the noun project as that is where the original designer got his assets from. You may need to get creative to solve this problem. You may need to use `Pixlr/editor` to manually change them if you can't find them, but make sure you ABSOLUTELY can't find them before doing this.

**Comment by giftedprimate** [comment]
@willweatherman Next time when you do a PR can you please throw a comment here using `@giftedprimate` letting me know, that way I am alerted when you are finished.

The commands need to be done as well, they are stored in `ui/src/assets/assets.js`.

```
cmdImages: {
    drop_item: 'https://res.cloudinary.com/deqjemwcu/image/upload/o_80/v1522345223/robotCommands/setDown.png',
    pick_up: 'https://res.cloudinary.com/deqjemwcu/image/upload/o_80/v1522345227/robotCommands/pickup.png',
    turn_right: 'https://res.cloudinary.com/deqjemwcu/image/upload/o_80/v1522345219/robotCommands/rightArrow.png',
    move_forward: 'https://res.cloudinary.com/deqjemwcu/image/upload/o_80/v1522345224/robotCommands/walk.png'
  },
```

Thanks!

**Comment by willweatherman** [comment]
@giftedprimate I created another pull request for this.

**Comment by giftedprimate** [comment]
@JWWeatherman This is deployed to pre-prod.

**Comment by JWWeatherman** [comment]
Looks awesome. Nice job doing that tedious work @willweatherman
