### ISSUE TITLE
The wrong levels are unlocked when you pass

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#642]
I don't have a solid repo of this, but hopefully it will be easy to track down. When passing the conditional levels around 12 and recursion around level 12 the wrong levels were unlocked.

If it's not an easily found bug with code review push this back to me and I'll do some more testing.

**Comment by giftedprimate** [comment]
I played through all the levels multiple times and have not been able to recreate this bug.

**Comment by JWWeatherman** [comment]
Ok, will keep an eye out for a repro, but I bet it was related to an old account.
