### ISSUE TITLE
1 Digit star system not unlocked after completing Code star system

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#643]
My account had already completed all of the code levels, but the 1 Digit star system wasn't unlocked. So I went to the conditionals planet and clicked on the (available) "next star system" tile. That brought me to the first level, but when I cilcked on my profile it shows that none of the planets are unlocked.

<img width="1343" alt="screen shot 2018-12-13 at 3 20 53 pm" src="https://user-images.githubusercontent.com/32912678/49965401-14879680-feeb-11e8-8257-b474aac3484e.png">

Then I returned back to the code star system, but the 1 digit star system is greyed out above, while still available on the tile.

<img width="866" alt="screen shot 2018-12-13 at 3 25 11 pm" src="https://user-images.githubusercontent.com/32912678/49965483-4dc00680-feeb-11e8-98f2-0c113fa9a515.png">

**Comment by giftedprimate** [comment]
@JWWeatherman I just recreated something similar. The problem is coming from the sandbox levels. I will create a different way to get those levels so that they are not part of the flow.

**Comment by giftedprimate** [comment]
@JWWeatherman removing the sandbox appears to fix the problem. I will deploy the app without the sandbox, then I will re-add it so that it is not part of the level flow.

**Comment by JWWeatherman** [comment]
Cool. Let’s also name it "Sandbox"

**Comment by JWWeatherman** [comment]
Very likely.

**Comment by giftedprimate** [comment]
k

**Comment by giftedprimate** [comment]
@JWWeatherman deployed to pre-prod (off scrub-through branch) and prod (off v0.04-beta branch)

When you get a chance can you see it the next level is unlocked. If it is not I suspect your stats table updated improperly to alleviate this try to play to first level of single digit.

**Comment by JWWeatherman** [comment]
Looks good.
