### ISSUE TITLE
Robot should be interactive

### ISSUE THREAD

**Issue by j-chimienti** [JWWeatherman/math_bot#664]
Suggestion from teacher friend:

Issue:

Homepage uninformative, and doesn't interact with user input as expected. Since robot moves, I expect something to happen when I click on him (and offer help). 

Lower level kids unfamiliar w/ program will start clicking, pressing buttons, and when no help or responses to inputs happen, will give up

<img width="1047" alt="screen shot 2018-12-18 at 9 55 54 am" src="https://user-images.githubusercontent.com/16620120/50162076-6e051200-02ab-11e9-9627-6c34cba16b0e.png">

**Comment by JWWeatherman** [comment]
Should we play the hint video if you click on the robot?

**Comment by JWWeatherman** [comment]
I think he’s taking about the white robot on the board? Love the way we clear main now. Very cool.

**Comment by giftedprimate** [comment]
Ah, makes sense.

**Comment by j-chimienti** [comment]
I was talking about the black robot, since its eyes moved, but yea is addressed now.
