### ISSUE TITLE
It isn't intuitive to navigate between planets

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#67]
![math_bot](https://user-images.githubusercontent.com/32912678/41126792-b7b63956-6a76-11e8-85b3-0de4185c221f.jpg)

Right now when a new planet is available to play it goes from very dark grey to black. As you can see in the attached image it is not obvious that the top planet is clickable. 

Here are a couple ideas:

1. At the end of the previous planet, where we select levels, the final level should look fun and interesting and say "next planet." This would allow the gamer to move directly into the first level on the next planet.
2. Let's make the planets different colors. The first planet could be purple and glow when selected. The second could be one of the other colors (maybe of the colors of the blocks) and glow when selected. Planets are grey until they are locked and then colored when they are unlocked.

**Comment by giftedprimate** [comment]
I'll build something today and get it pushed to the pre-prod site for your inspection. This can probably be released tomorrow.

(I added an `URGENT` label for this kind of issue)

**Comment by giftedprimate** [comment]
Master branch includes these changes. I also fixed some server bugs while I was at it.
