### ISSUE TITLE
Can not scroll above the functions

### ISSUE THREAD

**Issue by willweatherman** [JWWeatherman/math_bot#678]
If we delete the header in the screenshot and change the code to position the X button then we can scroll above and below the functions on both Ipad and touchpad laptops. @giftedprimate Do you think this is a good idea to try?

**Comment by giftedprimate** [comment]
@willweatherman this is solve in #635 (take a look at the screen shots there, it is also deployed to pre-prod).

That header portion is important when editing a function because it is where all the 'parameters' are located.

Closing since this is a mute issue after JW accepts #635
