### ISSUE TITLE
Richard Compensation Request Through 12/15

### ISSUE THREAD

**Issue by PedroXimenez** [JWWeatherman/math_bot#733]
Richard, we would like to keep up with this on a monthly basis, but for this request, please post your reward request and a brief explanation of the tasks completed for the following time periods:

8/16 - 9/15
9/16 - 10/15
10/16 - 11/15
11/16 - 12/15

When finished, please paste in your Indie Square wallet address that you want your tokens sent to and assign this issue to JW.

**Comment by giftedprimate** [comment]
510 hrs from 9/16 - 12/31 @ $60 hr = $30,600.00

All my work is recorded in issues and pull requests.

Thanks!

**Comment by PedroXimenez** [comment]
Excellent, thank you!

**Comment by giftedprimate** [comment]
@PedroXimenez I received the PU's, Thanks!
