### ISSUE TITLE
Bug when loading admin page

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#745]
@NateAgapi typed the magic word on the admin page and this is what it displayed (blank page with stars)

![oft8rqdb](https://user-images.githubusercontent.com/32912678/51007321-20c83900-1515-11e9-96c9-8f283c4faf16.jpg)

**Comment by giftedprimate** [comment]
@NateAgapi Can you try to delete your site data and try again...
 
1) Right click the browser window
2) Select inspect element
3) Click application (sometimes you will need to click the little '>>>' to get to it)
4) Click storage

You will need to re-authenticate. If the problem persists can you send me a screen shot of your console...

1) Right click the browser window
2) Select inspect element
3) Select console

Thanks for the feed back!

**Comment by NateAgapi** [comment]
This bug just went away. I noticed it went away before I even saw this. I didn't do anything for it to go away.

**Comment by giftedprimate** [comment]
@NateAgapi I love self destructive bugs! Thanks Nate.
