### ISSUE TITLE
Footer on the 10hours site

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#789]
Let's throw on a footer with two links:

Feedback (linked here: https://twitter.com/JWWeatherman_)

Donations (linked here:  https://tippin.me/@JWWeatherman_)

**Comment by giftedprimate** [comment]
@JWWeatherman there is a repo for this project in case you want to put this issue there.

**Comment by JWWeatherman** [comment]
Good call. Closing here.

**Comment by giftedprimate** [comment]
Sweet, thanks!
