### ISSUE TITLE
UI Nitpicks :]  The heading is a few pixels to tall

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#790]
The image on the left is the template site and on the right is our site:

<img width="408" alt="screen shot 2019-01-26 at 10 20 37 am" src="https://user-images.githubusercontent.com/32912678/51789185-357f1080-2154-11e9-93c4-0cb2e7100240.png">

**Comment by giftedprimate** [comment]
Dev nitpick :] wrong repo ;)

**Comment by JWWeatherman** [comment]
Dang it!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by JWWeatherman** [comment]
I'm going to close this anyway. It looks perfect on other devices and it looks so good in this case that it's not worth changing.
