### ISSUE TITLE
UI Nickpick :] The link needs a little more space and to be grey

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#791]
Let's add a little more padding between the Read link and the bottom of the listen button and also change the color to light grey:

<img width="415" alt="screen shot 2019-01-26 at 10 23 02 am" src="https://user-images.githubusercontent.com/32912678/51789219-8bec4f00-2154-11e9-97c0-fa8be88f68b3.png">

**Comment by giftedprimate** [comment]
Dev nitpick :] wrong repo ;{)

**Comment by JWWeatherman** [comment]
:]
