### ISSUE TITLE
play button disapears

### ISSUE THREAD

**Issue by eth-is-a-security** [JWWeatherman/math_bot#80]
bug: when you hit stop program while the robot is picking up or putting down the play button disappears and does not reappear.

**Comment by eth-is-a-security** [comment]
if you hit stop program while the robot is running into a wall the play button disappears and does not reappear.

**Comment by dy24703** [comment]
I just ran into this issue as well. 7/1/18

https://drive.google.com/open?id=1F5u3J2NnsTDZ08bfHbkBmbgsX4WYFO8P

Testing on Windows10-Firefox Browser (v. 61.0)

**Comment by giftedprimate** [comment]
This bug should be solved in the next release.

**Comment by giftedprimate** [comment]
Removing labels since there is still a case this can happen as notices in issue #181

**Comment by giftedprimate** [comment]
Fix is deployed!
