### ISSUE TITLE
Wait when the robot is placing a required number of blocks

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#9]
Levels that require the placement of 5 blocks can be passed if the robot is in the process of placing 7 blocks because as soon as 5 is reached the requirement is met.

Instead either the code that is checking the amount of blocks placed needs to be delayed to allow the robot time to place more blocks making the amount placed incorrect OR

The code that is checking the amount placed also needs to verify that the robot is not holding any objects. The problem with this solution is that in creates extra constraints on the student that are not obvious or intuitive. If the robot is programmed to pickup a large number, but place the correct number on the pile, the student has found a valid solution.

**Comment by giftedprimate** [comment]
This is not the case. The level cannot be passed unless the robot is carrying nothing.

**Comment by JWWeatherman** [comment]
Cool.
