### ISSUE TITLE
Add video hints 

### ISSUE THREAD

**Issue by JWWeatherman** [JWWeatherman/math_bot#99]
Display the number of stars with a question mark inside each in the robot dialog box (we should also drop this it 3 max) and allow the gamer to click on the stars to watch a hint video.

Hint videos should be cumulative so that every hint in the first video is also duplicated in the second and both the first and second video hints are duplicated in the third video.

When the gamer clicks on the stars one of the stars (starting on the left) turns grey and a video hint is displayed. After clicking 3 times the final hint video is played again on each additional click, but now that all 3 stars are grey they simply remain grey.

After 1 hour the stars should reset so that the gamer can repeat the level without hints and win all of the stars.

Some levels will only have a single hint. In those cases all 3 stars should be turned grey.

Levels with two video hints should loose one star on the first video and all 3 on the second video.

The image shows white ovals instead of yellow stars, but shows the location. They are also way too big and ugly. But developer art is fine for now.

We should also disable the ability to hide the dialogue box as this could cause confusion and has no real purpose.

![cursor_and_math_bot](https://user-images.githubusercontent.com/32912678/41480992-563a65c0-709e-11e8-9943-1ef1999749f4.jpg)

**Comment by smh69** [comment]
nicely done! can confirm is useful in production.
